/**
 * SYSTEM AGENT (v1 — deterministic, grounded)
 *
 * LoreBook's self-model. It explains HOW the app understood a message by
 * mapping what the pipeline produced to the concrete services/files/schemas
 * responsible — sourced from the `system_knowledge` table (with a built-in
 * fallback of the same facts so it works before the seed is applied).
 *
 * It deliberately produces observations only (no proposed actions) and never
 * asserts anything that isn't backed by a known system_knowledge fact. This is
 * the "do not hallucinate" guarantee: every claim cites a source file.
 */

import type {
  LoreAgent,
  LoreAgentInput,
  LoreAgentResult,
  LoreAgentObservation,
  LoreAgentEvidence,
} from '../loreAgentTypes';

interface KnowledgeFact {
  concept: string;
  description: string;
  sourceFile?: string;
  serviceName?: string;
  route?: string;
}

/**
 * Fallback facts (mirror the system_knowledge seed). Used when the table is
 * empty/unmigrated so the SystemAgent still explains accurately. These are
 * facts about code we control, not generated guesses.
 */
const FALLBACK_FACTS: Record<string, KnowledgeFact> = {
  memory_ingestion_pipeline: {
    concept: 'memory_ingestion_pipeline',
    description: 'Interpretation is orchestrated by loreInterpretationPipeline.ts (lexer → parser → mapper).',
    sourceFile: 'apps/server/src/services/pipeline/loreInterpretationPipeline.ts',
    serviceName: 'loreInterpretationPipeline',
    route: '/api/meaning',
  },
  entity_resolution: {
    concept: 'entity_resolution',
    description: 'Entities were detected and resolved by entityResolutionService.',
    sourceFile: 'apps/server/src/services/entityResolutionService.ts',
    serviceName: 'entityResolutionService',
    route: '/api/entity-resolution',
  },
  identity_collisions: {
    concept: 'identity_collisions',
    description: 'Identity collisions are flagged by identityCollisionService and must never auto-merge.',
    sourceFile: 'apps/server/src/services/meaning/identityCollisionService.ts',
    serviceName: 'identityCollisionService',
    route: '/api/entity-authority',
  },
  meaning_resolution: {
    concept: 'meaning_resolution',
    description: 'Contradictions and meaning were resolved by meaningResolutionService.',
    sourceFile: 'apps/server/src/services/meaning/meaningResolutionService.ts',
    serviceName: 'meaningResolutionService',
    route: '/api/meaning',
  },
  identity_corrections_audit: {
    concept: 'identity_corrections_audit',
    description: 'Truth-state changes are audited in cognition_mutations via CorrectionAuthority.',
    sourceFile: 'apps/server/src/services/provenance/CorrectionAuthority.ts',
    serviceName: 'correctionAuthority',
    route: '/api/corrections',
  },
  memory_review_queue: {
    concept: 'memory_review_queue',
    description: 'Proposed memories await confirmation in the Memory Review Queue.',
    sourceFile: 'apps/server/src/routes/memoryReviewQueue.ts',
    serviceName: 'memoryReviewQueue',
    route: '/api/mrq',
  },
  narrative_summaries: {
    concept: 'narrative_summaries',
    description: 'Narrative summaries are generated by StoryOfSelfEngine.',
    sourceFile: 'apps/server/src/services/storyOfSelf/storyOfSelfEngine.ts',
    serviceName: 'StoryOfSelfEngine',
    route: '/api/story-of-self',
  },
};

class SystemAgent implements LoreAgent {
  readonly name = 'SystemAgent';

  shouldRun(input: Omit<LoreAgentInput, 'tools'>): boolean {
    const meaning = input.pipelineResult.meaning;
    if (!meaning) return false;
    return (
      meaning.resolvedEntities.length > 0 ||
      meaning.memoryReviewCandidates.length > 0 ||
      meaning.contradictions.length > 0 ||
      meaning.identityCollisions.length > 0 ||
      meaning.resolvedEvents.length > 0
    );
  }

  async run(input: LoreAgentInput): Promise<LoreAgentResult> {
    const startedAt = new Date().toISOString();
    const { meaning } = input.pipelineResult;

    // Load the self-model from the DB; merge over the fallback facts.
    const facts: Record<string, KnowledgeFact> = { ...FALLBACK_FACTS };
    try {
      const rows = await input.tools.getSystemKnowledge();
      for (const row of rows) {
        const concept = String(row.concept ?? '');
        if (!concept) continue;
        facts[concept] = {
          concept,
          description: String(row.description ?? ''),
          sourceFile: (row.source_file as string | undefined) ?? undefined,
          serviceName: (row.service_name as string | undefined) ?? undefined,
          route: (row.route as string | undefined) ?? undefined,
        };
      }
    } catch {
      // Fallback facts already in place.
    }

    const observations: LoreAgentObservation[] = [];
    const evidence: LoreAgentEvidence[] = [];

    const cite = (fact: KnowledgeFact, summary: string) => {
      const ev: LoreAgentEvidence = {
        kind: 'system_knowledge',
        ref: fact.serviceName ?? fact.concept,
        detail: fact.description,
        sourceFile: fact.sourceFile,
      };
      observations.push({ kind: 'system_explanation', summary, confidence: 1, evidence: [ev] });
      evidence.push(ev);
    };

    // Always explain the pipeline that ran.
    const phases = (await input.tools.getPipelineTrace(input.userId, input.messageId))?.phases ?? ['lexer', 'parser', 'mapper'];
    cite(
      facts.memory_ingestion_pipeline,
      `LoreBook interpreted this message through the pipeline: ${phases.join(' → ')}.`
    );

    if ((meaning?.resolvedEntities.length ?? 0) > 0) {
      cite(facts.entity_resolution, `${meaning!.resolvedEntities.length} entity(ies) were resolved here.`);
    }
    if ((meaning?.identityCollisions.length ?? 0) > 0) {
      cite(facts.identity_collisions, `An identity collision was detected and routed for review (never auto-merged).`);
    }
    if ((meaning?.contradictions.length ?? 0) > 0) {
      cite(facts.meaning_resolution, `A contradiction was detected.`);
      cite(facts.identity_corrections_audit, `Any correction is audited in cognition_mutations.`);
    }
    if ((meaning?.memoryReviewCandidates.length ?? 0) > 0) {
      cite(facts.memory_review_queue, `Memory candidates were proposed for confirmation.`);
    }
    if ((meaning?.resolvedEvents.length ?? 0) > 0) {
      cite(facts.narrative_summaries, `Events here may feed the narrative summary.`);
    }

    return {
      agentName: this.name,
      runId: input.runId,
      observations,
      proposedActions: [],
      confidence: 0.95,
      evidence,
      warnings: [],
      startedAt,
      completedAt: new Date().toISOString(),
    };
  }
}

export const systemAgent = new SystemAgent();
