import { useState, useCallback, useEffect, useRef } from 'react';
import { useAuth } from '../../../lib/supabase';
import { fetchJson } from '../../../lib/api';
import { config } from '../../../config/env';
import { runtimeDiagnostics } from '../services/runtimeDiagnostics';
import { threadPersistenceTracker } from '../services/threadPersistenceTracker';
import type { Message } from '../message/ChatMessage';

export type ChatThread = {
  id: string;
  title: string;
  /** Short category label generated by ConversationTitleService, e.g. "Architecture Session" */
  subtitle?: string;
  /** Top entity names extracted by ingestion pipeline — people, places recurring in this thread */
  dominantEntities?: string[];
  messages: Message[];
  updatedAt: string;
};

// ── Storage keys ─────────────────────────────────────────────────────────────
const STORAGE_PREFIX = 'lorekeeper_chat_threads_';
const LAST_THREAD_KEY = 'lorekeeper_chat_last_thread_';

function storageKey(userId: string | undefined) {
  return `${STORAGE_PREFIX}${userId ?? 'guest'}`;
}
function lastThreadKey(userId: string | undefined) {
  return `${LAST_THREAD_KEY}${userId ?? 'guest'}`;
}

// ── Serialisation helpers ─────────────────────────────────────────────────────
function parseStoredMessage(msg: any): Message {
  return { ...msg, timestamp: msg.timestamp ? new Date(msg.timestamp) : new Date() };
}

function messagesToJson(messages: Message[]) {
  return messages.map((m) => ({
    ...m,
    timestamp: m.timestamp instanceof Date ? m.timestamp.toISOString() : m.timestamp,
  }));
}

function dbRowToThread(t: any): ChatThread {
  const msgs: any[] = t.metadata?.messages ?? [];
  return {
    id: t.id,
    title: t.title || 'New chat',
    subtitle: t.metadata?.subtitle as string | undefined,
    dominantEntities: Array.isArray(t.metadata?.dominantEntities) ? t.metadata.dominantEntities : undefined,
    messages: msgs.map(parseStoredMessage),
    updatedAt: t.updated_at || t.created_at || new Date().toISOString(),
  };
}

// ── Read Supabase access_token from localStorage synchronously (for keepalive saves) ──
function getTokenSync(): string | null {
  try {
    const key = Object.keys(localStorage).find(
      (k) => k.startsWith('sb-') && k.endsWith('-auth-token')
    );
    if (!key) return null;
    const raw = localStorage.getItem(key);
    if (!raw) return null;
    return JSON.parse(raw)?.access_token ?? null;
  } catch {
    return null;
  }
}

// ── Pending-save record ───────────────────────────────────────────────────────
type PendingSave = { timer: ReturnType<typeof setTimeout>; snap: any[] };

export const useChatThreads = () => {
  const { user, loading: authLoading } = useAuth();
  const userId = user?.id;
  const isAuthenticated = !!userId;

  const [threads, setThreads] = useState<ChatThread[]>([]);
  const [currentThreadId, setCurrentThreadIdState] = useState<string | null>(null);
  // threadsLoading: true until we've finished the FIRST authoritative load (backend or localStorage).
  const [threadsLoading, setThreadsLoading] = useState(true);
  // threadsReady: true after a successful backend load — used to gate "thread not found" redirects.
  const [threadsReady, setThreadsReady] = useState(false);

  const saveDebounceRef = useRef<Record<string, PendingSave>>({});
  const currentThreadIdRef = useRef<string | null>(null);

  useEffect(() => {
    currentThreadIdRef.current = currentThreadId;
  }, [currentThreadId]);

  // ── Guest localStorage helpers ──────────────────────────────────────────────

  const persistLocal = useCallback(
    (nextThreads: ChatThread[], lastId: string | null) => {
      if (!isAuthenticated && typeof window !== 'undefined') {
        try {
          localStorage.setItem(
            storageKey(userId),
            JSON.stringify(nextThreads.map((t) => ({ ...t, messages: messagesToJson(t.messages) })))
          );
          if (lastId) localStorage.setItem(lastThreadKey(userId), lastId);
          else localStorage.removeItem(lastThreadKey(userId));
        } catch (_) {}
      }
    },
    [isAuthenticated, userId]
  );

  const loadFromLocalStorage = useCallback(() => {
    try {
      const raw = localStorage.getItem(storageKey(userId));
      const parsed: ChatThread[] = raw ? JSON.parse(raw) : [];
      const hydrated = parsed.map((t) => ({
        ...t,
        messages: (t.messages || []).map(parseStoredMessage),
        updatedAt: t.updatedAt || new Date(0).toISOString(),
      }));
      setThreads(hydrated);
      for (const t of hydrated) threadPersistenceTracker.markRestoredFromLocal(t.id);
      const last = localStorage.getItem(lastThreadKey(userId));
      setCurrentThreadIdState(last ?? null);
    } catch {
      setThreads([]);
      setCurrentThreadIdState(null);
    } finally {
      setThreadsLoading(false);
    }
  }, [userId]);

  // ── Backend helpers ─────────────────────────────────────────────────────────

  const loadFromBackend = useCallback(async () => {
    runtimeDiagnostics.record('backend_load_start');
    runtimeDiagnostics.startTimer('backend_load');
    setThreadsLoading(true);
    try {
      const data = await fetchJson<{ threads: any[]; success: boolean }>('/api/conversation/threads');
      const loaded = (data.threads || []).map(dbRowToThread);
      setThreads(loaded);
      for (const t of loaded) threadPersistenceTracker.markRestoredFromBackend(t.id);
      const last = localStorage.getItem(lastThreadKey(userId));
      if (last && loaded.some((t) => t.id === last)) {
        setCurrentThreadIdState(last);
      } else {
        setCurrentThreadIdState(null);
      }
      setThreadsReady(true);
      runtimeDiagnostics.recordTimed('backend_load_complete', 'backend_load', {
        meta: { threadCount: loaded.length },
      });
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      runtimeDiagnostics.recordTimed('backend_load_fallback', 'backend_load', {
        meta: { error: errMsg },
      });
      threadPersistenceTracker.markOffline();
      // Backend unreachable — fall back to localStorage.
      // Log in dev so the developer knows (not an error in offline/guest flow).
      if (config.env.isDevelopment) {
        console.warn('[useChatThreads] Backend unreachable, falling back to localStorage:', errMsg);
      }
      loadFromLocalStorage();
    } finally {
      setThreadsLoading(false);
    }
  }, [userId, loadFromLocalStorage]);

  // ── Boot: wait for auth to resolve, then load from the right source ─────────
  useEffect(() => {
    if (authLoading) return;
    if (isAuthenticated) {
      loadFromBackend();
    } else {
      loadFromLocalStorage();
    }
  }, [isAuthenticated, authLoading]); // eslint-disable-line react-hooks/exhaustive-deps

  // ── Save flush helpers ──────────────────────────────────────────────────────

  const flushSave = useCallback((id: string) => {
    const pending = saveDebounceRef.current[id];
    if (!pending) return;
    clearTimeout(pending.timer);
    delete saveDebounceRef.current[id];
    runtimeDiagnostics.record('flush_save', { threadId: id });
    threadPersistenceTracker.markPersisting(id);
    fetchJson(`/api/conversation/threads/${id}`, {
      method: 'PATCH',
      body: JSON.stringify({ messages: pending.snap }),
    }).then(() => {
      threadPersistenceTracker.markPersisted(id);
    }).catch((err: unknown) => {
      const errMsg = err instanceof Error ? err.message : String(err);
      runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'flush_save', error: errMsg } });
      threadPersistenceTracker.markSyncFailed(id, errMsg);
      console.error('[useChatThreads] flushSave failed for thread', id, errMsg);
    });
  }, []);

  const flushAllPendingKeepalive = useCallback(() => {
    const token = getTokenSync();
    const apiBase = config.api.url || '';
    Object.entries(saveDebounceRef.current).forEach(([id, pending]) => {
      clearTimeout(pending.timer);
      delete saveDebounceRef.current[id];
      try {
        fetch(`${apiBase}/api/conversation/threads/${id}`, {
          method: 'PATCH',
          headers: {
            'Content-Type': 'application/json',
            ...(token ? { Authorization: `Bearer ${token}` } : {}),
          },
          body: JSON.stringify({ messages: pending.snap }),
          keepalive: true,
        });
      } catch (_) {}
    });
  }, []);

  useEffect(() => {
    window.addEventListener('beforeunload', flushAllPendingKeepalive);
    return () => window.removeEventListener('beforeunload', flushAllPendingKeepalive);
  }, [flushAllPendingKeepalive]);

  // ── Public API ──────────────────────────────────────────────────────────────

  const createThread = useCallback((): string => {
    const id = crypto.randomUUID();
    const thread: ChatThread = {
      id,
      title: 'New chat',
      messages: [],
      updatedAt: new Date().toISOString(),
    };
    setThreads((prev) => {
      const next = [thread, ...prev];
      if (!isAuthenticated) persistLocal(next, id);
      return next;
    });
    setCurrentThreadIdState(id);
    if (isAuthenticated) {
      threadPersistenceTracker.markPersistPending(id, 0);
      localStorage.setItem(lastThreadKey(userId), id);
      fetchJson('/api/conversation/threads', {
        method: 'POST',
        body: JSON.stringify({ id, title: 'New chat' }),
      }).then(() => {
        threadPersistenceTracker.markPersisted(id);
      }).catch((err: unknown) => {
        const errMsg = err instanceof Error ? err.message : String(err);
        runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'create_thread', error: errMsg } });
        threadPersistenceTracker.markSyncFailed(id, errMsg);
        console.error('[useChatThreads] createThread persist failed:', errMsg);

      });
    } else {
      threadPersistenceTracker.markLocalOnly(id);
    }
    return id;
  }, [isAuthenticated, userId, persistLocal]);

  const getThread = useCallback(
    (id: string) => threads.find((t) => t.id === id),
    [threads]
  );

  const switchThread = useCallback(
    (id: string) => {
      setCurrentThreadIdState(id);
      if (isAuthenticated) {
        localStorage.setItem(lastThreadKey(userId), id);
      } else {
        persistLocal(threads, id);
      }
    },
    [isAuthenticated, userId, threads, persistLocal]
  );

  const updateThread = useCallback(
    (id: string, payload: {
      title?: string;
      /** subtitle is local-only — server persists it via the title service, not via this PATCH */
      subtitle?: string;
      dominantEntities?: string[];
      messages?: Message[];
      updatedAt?: string;
    }) => {
      const updatedAt = payload.updatedAt ?? new Date().toISOString();
      setThreads((prev) => {
        const next = prev.map((t) =>
          t.id === id
            ? {
                ...t,
                ...(payload.title !== undefined && { title: payload.title }),
                ...(payload.subtitle !== undefined && { subtitle: payload.subtitle }),
                ...(payload.dominantEntities !== undefined && { dominantEntities: payload.dominantEntities }),
                ...(payload.messages !== undefined && { messages: payload.messages }),
                updatedAt,
              }
            : t
        );
        if (!isAuthenticated) persistLocal(next, currentThreadIdRef.current);
        return next;
      });

      if (isAuthenticated) {
        if (payload.title !== undefined) {
          fetchJson(`/api/conversation/threads/${id}`, {
            method: 'PATCH',
            body: JSON.stringify({ title: payload.title }),
          }).catch((err: unknown) => {
            const errMsg = err instanceof Error ? err.message : String(err);
            runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'update_title', error: errMsg } });
          });
        }
        // subtitle is NOT sent here — server already persisted it via the title service
        if (payload.messages !== undefined) {
          const existing = saveDebounceRef.current[id];
          if (existing) clearTimeout(existing.timer);
          const snap = messagesToJson(payload.messages);
          threadPersistenceTracker.markPersistPending(id, snap.length);
          saveDebounceRef.current[id] = {
            snap,
            timer: setTimeout(() => {
              delete saveDebounceRef.current[id];
              threadPersistenceTracker.markPersisting(id);
              fetchJson(`/api/conversation/threads/${id}`, {
                method: 'PATCH',
                body: JSON.stringify({ messages: snap }),
              }).then(() => {
                threadPersistenceTracker.markPersisted(id);
              }).catch((err: unknown) => {
                const errMsg = err instanceof Error ? err.message : String(err);
                runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'debounced_save', error: errMsg } });
                threadPersistenceTracker.markSyncFailed(id, errMsg);
                console.error('[useChatThreads] Debounced save failed for thread', id, errMsg);
              });
            }, 1500),
          };
        }
      }
    },
    [isAuthenticated, persistLocal]
  );

  /**
   * Rename a thread — optimistic local update + PATCH /threads/:id/title.
   * The title endpoint marks titleSource: 'user' so auto-generation is suppressed forever.
   */
  const renameThread = useCallback(
    (id: string, title: string) => {
      setThreads((prev) =>
        prev.map((t) => (t.id === id ? { ...t, title } : t))
      );
      if (isAuthenticated) {
        fetchJson(`/api/conversation/threads/${id}/title`, {
          method: 'PATCH',
          body: JSON.stringify({ title }),
        }).catch((err: unknown) => {
          const errMsg = err instanceof Error ? err.message : String(err);
          runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'rename_thread', error: errMsg } });
          console.error('[useChatThreads] renameThread failed:', errMsg);
        });
      }
    },
    [isAuthenticated]
  );

  const deleteThread = useCallback(
    (id: string) => {
      const pending = saveDebounceRef.current[id];
      if (pending) {
        clearTimeout(pending.timer);
        delete saveDebounceRef.current[id];
      }
      setThreads((prev) => {
        const next = prev.filter((t) => t.id !== id);
        if (!isAuthenticated) persistLocal(next, currentThreadIdRef.current);
        return next;
      });
      if (currentThreadIdRef.current === id) {
        setCurrentThreadIdState(null);
        if (isAuthenticated) localStorage.removeItem(lastThreadKey(userId));
      }
      threadPersistenceTracker.remove(id);
      if (isAuthenticated) {
        fetchJson(`/api/conversation/threads/${id}`, { method: 'DELETE' }).catch((err: unknown) => {
          const errMsg = err instanceof Error ? err.message : String(err);
          runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'delete_thread', error: errMsg } });
          console.error('[useChatThreads] deleteThread failed:', errMsg);
        });
      }
    },
    [isAuthenticated, userId, persistLocal]
  );

  const setCurrentThreadId = useCallback(
    (id: string | null) => {
      setCurrentThreadIdState(id);
      if (isAuthenticated) {
        if (id) localStorage.setItem(lastThreadKey(userId), id);
        else localStorage.removeItem(lastThreadKey(userId));
      } else {
        persistLocal(threads, id);
      }
    },
    [isAuthenticated, userId, threads, persistLocal]
  );

  const loadThreads = useCallback(() => {
    if (isAuthenticated) return loadFromBackend();
    loadFromLocalStorage();
    return Promise.resolve();
  }, [isAuthenticated, loadFromBackend, loadFromLocalStorage]);

  return {
    threads,
    threadsLoading,
    threadsReady,
    currentThreadId,
    setCurrentThreadId,
    createThread,
    getThread,
    switchThread,
    updateThread,
    renameThread,
    deleteThread,
    flushSave,
    loadThreads,
  };
};
