import { useState, useCallback, useEffect, useRef } from 'react';
import { useAuth } from '../../../lib/supabase';
import { config } from '../../../config/env';
import { store } from '../../../store';
import { chatApi } from '../../../store/api/chatApi';
import { useAppDispatch, useAppSelector } from '../../../store/hooks';
import {
  setCurrentThreadId as setCurrentThreadIdAction,
  setThreadError,
  clearThreadError,
} from '../../../store/slices/chatSlice';
import { selectCurrentThreadId, selectThreadError } from '../../../store/selectors';
import { mutationErrorMessage, mutationErrorStatus } from '../../../store/rtkMutationUtils';
import { isFetchJsonError } from '../../../store/api/baseApi';
import { runtimeDiagnostics } from '../services/runtimeDiagnostics';
import { getBackendUnavailable } from '../../../contexts/MockDataContext';
import { isBackendConnectionError } from '../../../lib/backendErrorDisplay';
import { threadPersistenceTracker } from '../services/threadPersistenceTracker';
import {
  isDemoChatMockup,
  seedDemoChatThreadsIfEmpty,
} from '../../../services/demoChatSimulation';
import type { Message } from '../message/ChatMessage';
import {
  DRAFT_THREAD_TITLE,
  isGenericThreadTitle,
  normalizeThreadTitle,
  deriveTitleFromMessages,
} from '../utils/threadTitleUtils';
import { dedupeConversationThreads, ensureLocalUniqueTitle } from '../utils/threadDedupeUtils';
import { mergeLoadedThreadsWithHydrated } from '../utils/mergeLoadedThreadsWithHydrated';
import { mergeThreadMessages, countMissingAssistantTurns } from '../utils/mergeThreadMessages';
import { mapDbMessageRow } from '../utils/mapDbMessageRow';
import {
  persistAuthThreadCache,
  readAuthThreadFromCache,
} from '../utils/threadLocalCache';

export type ChatThread = {
  id: string;
  title: string;
  /** Short category label generated by ConversationTitleService, e.g. "Architecture Session" */
  subtitle?: string;
  /** Top entity names extracted by ingestion pipeline — people, places recurring in this thread */
  dominantEntities?: string[];
  messages: Message[];
  updatedAt: string;
  /** Server-side message count — used for sidebar filtering without hydrating messages */
  messageCount?: number;
};

// ── Storage keys ─────────────────────────────────────────────────────────────
const STORAGE_PREFIX = 'lorekeeper_chat_threads_';
const LAST_THREAD_KEY = 'lorekeeper_chat_last_thread_';

function storageKey(userId: string | undefined) {
  return `${STORAGE_PREFIX}${userId ?? 'guest'}`;
}
function lastThreadKey(userId: string | undefined) {
  return `${LAST_THREAD_KEY}${userId ?? 'guest'}`;
}

// ── Serialisation helpers ─────────────────────────────────────────────────────
function parseStoredMessage(msg: any): Message {
  return { ...msg, timestamp: msg.timestamp ? new Date(msg.timestamp) : new Date() };
}

function messagesToJson(messages: Message[]) {
  return messages.map((m) => ({
    ...m,
    timestamp: m.timestamp instanceof Date ? m.timestamp.toISOString() : m.timestamp,
  }));
}

function dbRowToThread(t: any): ChatThread {
  const messageCount = typeof t.message_count === 'number' ? t.message_count : undefined;
  const thread: ChatThread = {
    id: t.id,
    title: t.title || DRAFT_THREAD_TITLE,
    subtitle: t.metadata?.subtitle as string | undefined,
    dominantEntities: Array.isArray(t.metadata?.dominantEntities) ? t.metadata.dominantEntities : undefined,
    messages: [],
    updatedAt: t.updated_at || t.created_at || new Date().toISOString(),
    ...(messageCount !== undefined ? { messageCount } : {}),
  };
  return normalizeThreadTitle(thread);
}

function dbMessageToMessage(row: Parameters<typeof mapDbMessageRow>[0]): Message {
  return mapDbMessageRow(row);
}

const STALE_EMPTY_THRESHOLD_MS = 24 * 60 * 60 * 1000; // 24 hours

/** Guest-only: hide stale empty drafts from localStorage. Server threads are never age-filtered. */
function isUsableGuestThread(t: ChatThread): boolean {
  if ((t.messages?.length ?? 0) > 0) return true;
  if ((t.messageCount ?? 0) > 0) return true;
  const age = Date.now() - new Date(t.updatedAt).getTime();
  return age < STALE_EMPTY_THRESHOLD_MS;
}

/** Deduplicates threads by ID, identical conversations, and extra empty drafts. */
function dedupeThreads(threads: ChatThread[]): ChatThread[] {
  return dedupeConversationThreads(threads);
}

function sortThreadsByActivity(threads: ChatThread[]): ChatThread[] {
  return [...threads].sort(
    (a, b) => new Date(b.updatedAt).getTime() - new Date(a.updatedAt).getTime()
  );
}

async function fetchThreadsPage(args: { limit?: number; cursor?: string | null }) {
  const result = await store.dispatch(
    chatApi.endpoints.getThreads.initiate(args, { forceRefetch: true })
  );
  if (result.error) {
    const err = result.error;
    const message = isFetchJsonError(err)
      ? err.message
      : typeof (err as { message?: unknown }).message === 'string'
        ? (err as { message: string }).message
        : 'Failed to load threads';
    throw new Error(message);
  }
  return result.data!;
}

export const useChatThreads = () => {
  const { user, loading: authLoading } = useAuth();
  const userId = user?.id;
  const isAuthenticated = !!userId;
  const dispatch = useAppDispatch();
  const currentThreadId = useAppSelector(selectCurrentThreadId);
  const lastError = useAppSelector(selectThreadError);

  const [threads, setThreads] = useState<ChatThread[]>([]);
  const [threadsHasMore, setThreadsHasMore] = useState(false);
  const [threadsTotal, setThreadsTotal] = useState<number | null>(null);
  const [threadsLoadingMore, setThreadsLoadingMore] = useState(false);
  const threadsNextCursorRef = useRef<string | null>(null);
  // threadsLoading: true until we've finished the FIRST authoritative load (backend or localStorage).
  const [threadsLoading, setThreadsLoading] = useState(true);
  // threadsReady: true after a successful backend load — used to gate "thread not found" redirects.
  const [threadsReady, setThreadsReady] = useState(false);

  const currentThreadIdRef = useRef<string | null>(null);
  const threadsRef = useRef<ChatThread[]>([]);

  useEffect(() => { threadsRef.current = threads; }, [threads]);

  useEffect(() => {
    currentThreadIdRef.current = currentThreadId;
  }, [currentThreadId]);

  const applyCurrentThreadId = useCallback(
    (id: string | null) => {
      dispatch(setCurrentThreadIdAction(id));
    },
    [dispatch]
  );

  // ── Guest localStorage helpers ──────────────────────────────────────────────

  const persistLocal = useCallback(
    (nextThreads: ChatThread[], lastId: string | null) => {
      if (!isAuthenticated && typeof window !== 'undefined') {
        try {
          localStorage.setItem(
            storageKey(userId),
            JSON.stringify(nextThreads.map((t) => ({ ...t, messages: messagesToJson(t.messages) })))
          );
          if (lastId) localStorage.setItem(lastThreadKey(userId), lastId);
          else localStorage.removeItem(lastThreadKey(userId));
        } catch (_) {}
      }
    },
    [isAuthenticated, userId]
  );

  const loadFromLocalStorage = useCallback(() => {
    try {
      const raw = localStorage.getItem(storageKey(userId));
      const parsed: ChatThread[] = raw ? JSON.parse(raw) : [];
      const hydrated = dedupeThreads(
        seedDemoChatThreadsIfEmpty(
          parsed
            .map((t) => ({
              ...t,
              messages: (t.messages || []).map(parseStoredMessage),
              updatedAt: t.updatedAt || new Date(0).toISOString(),
            }))
            .filter(isUsableGuestThread)
        )
      );
      setThreads(hydrated);
      for (const t of hydrated) threadPersistenceTracker.markRestoredFromLocal(t.id);
      const last = localStorage.getItem(lastThreadKey(userId));
      applyCurrentThreadId(last ?? null);
      if (isDemoChatMockup()) {
        setThreadsReady(true);
        if (!raw && hydrated.length > 0) {
          persistLocal(hydrated, last ?? null);
        }
      }
    } catch {
      setThreads([]);
      applyCurrentThreadId(null);
    } finally {
      setThreadsLoading(false);
    }
  }, [userId]);

  // ── Backend helpers ─────────────────────────────────────────────────────────

  const loadFromBackend = useCallback(async () => {
    runtimeDiagnostics.record('backend_load_start');
    runtimeDiagnostics.startTimer('backend_load');
    setThreadsLoading(true);
    try {
      // Repair + recover before listing — ensures nothing is orphaned or drifted.
      await store.dispatch(chatApi.endpoints.repairChatHealth.initiate()).unwrap().catch(() => {});
      await store.dispatch(chatApi.endpoints.recoverThreadOrphans.initiate()).unwrap().catch(() => {});

      const data = await fetchThreadsPage({ limit: 30 });
      const loaded = dedupeThreads((data.threads || []).map(dbRowToThread));
      setThreads((prev) => {
        const merged = mergeLoadedThreadsWithHydrated(loaded, prev);
        threadsRef.current = merged;
        return merged;
      });
      threadsNextCursorRef.current = data.nextCursor ?? null;
      setThreadsHasMore(data.hasMore ?? false);
      setThreadsTotal(typeof data.total === 'number' ? data.total : loaded.length);
      for (const t of loaded) threadPersistenceTracker.markRestoredFromBackend(t.id);
      // Upgrade legacy generic titles in the background.
      for (const t of loaded) {
        const rawTitle = (data.threads || []).find((row: any) => row.id === t.id)?.title;
        if (isGenericThreadTitle(rawTitle) && !isGenericThreadTitle(t.title) && t.messages.length > 0) {
          void store
            .dispatch(chatApi.endpoints.patchThreadTitle.initiate({ threadId: t.id, title: t.title }))
            .unwrap()
            .catch(() => {});
        }
      }
      const last = localStorage.getItem(lastThreadKey(userId));
      if (last && loaded.some((t) => t.id === last)) {
        applyCurrentThreadId(last);
      } else {
        applyCurrentThreadId(null);
      }
      setThreadsReady(true);
      dispatch(clearThreadError());
      runtimeDiagnostics.recordTimed('backend_load_complete', 'backend_load', {
        meta: { threadCount: loaded.length },
      });
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      runtimeDiagnostics.recordTimed('backend_load_fallback', 'backend_load', {
        meta: { error: errMsg },
      });
      threadPersistenceTracker.markOffline();
      // Backend unreachable — fall back to localStorage.
      // Log in dev so the developer knows (not an error in offline/guest flow).
      if (config.env.isDevelopment) {
        console.warn('[useChatThreads] Backend unreachable, falling back to localStorage:', errMsg);
      }
      loadFromLocalStorage();
    } finally {
      setThreadsLoading(false);
    }
  }, [userId, loadFromLocalStorage, dispatch]);

  const loadMoreThreads = useCallback(async () => {
    if (isDemoChatMockup() || !isAuthenticated || threadsLoadingMore || !threadsHasMore) return;
    const cursor = threadsNextCursorRef.current;
    if (!cursor) return;

    setThreadsLoadingMore(true);
    try {
      const data = await fetchThreadsPage({ limit: 30, cursor });
      const page = dedupeThreads((data.threads || []).map(dbRowToThread));
      setThreads((prev) => {
        const seen = new Set(prev.map((t) => t.id));
        const merged = [...prev, ...page.filter((t) => !seen.has(t.id))];
        threadsRef.current = merged;
        return merged;
      });
      for (const t of page) threadPersistenceTracker.markRestoredFromBackend(t.id);
      threadsNextCursorRef.current = data.nextCursor ?? null;
      setThreadsHasMore(data.hasMore ?? false);
    } catch (err: unknown) {
      const errMsg = err instanceof Error ? err.message : String(err);
      if (!getBackendUnavailable() || !isBackendConnectionError(errMsg)) {
        dispatch(setThreadError(errMsg));
      }
      runtimeDiagnostics.record('backend_load_error', { meta: { op: 'load_more_threads', error: errMsg } });
    } finally {
      setThreadsLoadingMore(false);
    }
  }, [isAuthenticated, threadsHasMore, threadsLoadingMore, dispatch]);

  // ── Boot: wait for auth to resolve, then load from the right source ─────────
  useEffect(() => {
    if (authLoading) return;
    if (isAuthenticated) {
      loadFromBackend();
    } else {
      loadFromLocalStorage();
    }
  }, [isAuthenticated, authLoading]); // eslint-disable-line react-hooks/exhaustive-deps

  // Messages persist via chat_messages on the server (omegaChatService). Client only bumps activity.
  const flushSave = useCallback((_id: string) => {
    // No-op — P2 removed metadata.messages dual-write.
  }, []);

  // ── Public API ──────────────────────────────────────────────────────────────

  const createThread = useCallback((): string => {
    // Reuse the most recent thread if it is still empty — prevents orphan accumulation
    // when the user navigates to /chat repeatedly before sending any message.
    const latest = threadsRef.current[0];
    if (latest && latest.messages.length === 0 && isGenericThreadTitle(latest.title)) {
      applyCurrentThreadId(latest.id);
      if (isAuthenticated) localStorage.setItem(lastThreadKey(userId), latest.id);
      return latest.id;
    }

    const id = crypto.randomUUID();
    const thread: ChatThread = {
      id,
      title: DRAFT_THREAD_TITLE,
      messages: [],
      updatedAt: new Date().toISOString(),
    };
    setThreads((prev) => {
      const next = [thread, ...prev];
      if (!isAuthenticated) persistLocal(next, id);
      return next;
    });
    applyCurrentThreadId(id);
    if (isAuthenticated && !isDemoChatMockup()) {
      threadPersistenceTracker.markPersistPending(id, 0);
      localStorage.setItem(lastThreadKey(userId), id);
      void store
        .dispatch(chatApi.endpoints.createThread.initiate({ id, title: DRAFT_THREAD_TITLE }))
        .unwrap()
        .then(() => {
          threadPersistenceTracker.markPersisted(id);
        })
        .catch((err: unknown) => {
          const errMsg = mutationErrorMessage(err);
          runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'create_thread', error: errMsg } });
          threadPersistenceTracker.markSyncFailed(id, errMsg);
          console.error('[useChatThreads] createThread persist failed:', errMsg);
        });
    } else {
      threadPersistenceTracker.markLocalOnly(id);
    }
    return id;
  }, [isAuthenticated, userId, persistLocal]);

  const getThread = useCallback(
    (id: string) => threadsRef.current.find((t) => t.id === id),
    []
  );

  const hydrateThreadMessages = useCallback(
    async (id: string): Promise<ChatThread | null> => {
      const existing = threadsRef.current.find((t) => t.id === id);
      if (isDemoChatMockup()) {
        return existing ?? null;
      }
      let ensuredMeta: { title?: string; subtitle?: string; updatedAt?: string } = {};
      try {
        const ensured = await store
          .dispatch(chatApi.endpoints.ensureThreadVisible.initiate(id))
          .unwrap();
        if (ensured.success && ensured.thread) {
          ensuredMeta = {
            title: ensured.thread.title,
            subtitle: ensured.thread.subtitle,
            updatedAt: ensured.thread.updatedAt,
          };
        }
      } catch {
        // Non-fatal — messages fetch may still succeed
      }

      try {
        const result = await store
          .dispatch(chatApi.endpoints.getThreadMessages.initiate(id, { forceRefetch: true }))
          .unwrap();
        if (!result.success) return null;

        let messages = (result.messages || []).map(dbMessageToMessage);
        const localMessages = existing?.messages ?? [];
        const cachedThread = userId ? readAuthThreadFromCache(userId, id) : null;
        const cacheMessages = cachedThread?.messages ?? [];

        messages = mergeThreadMessages(localMessages, messages);
        if (cacheMessages.length > 0) {
          messages = mergeThreadMessages(cacheMessages, messages);
        }

        // If server snapshot is still missing assistant replies, keep local cache entirely.
        if (
          countMissingAssistantTurns(messages) > countMissingAssistantTurns(localMessages) &&
          localMessages.length > 0
        ) {
          messages = mergeThreadMessages(localMessages, messages);
        }

        if (messages.length === 0) {
          let emptyThread: ChatThread | null = null;
          setThreads((prev) => {
            const row = prev.find((t) => t.id === id);
            emptyThread = {
              id,
              title: ensuredMeta.title || row?.title || existing?.title || DRAFT_THREAD_TITLE,
              subtitle: ensuredMeta.subtitle ?? row?.subtitle ?? existing?.subtitle,
              dominantEntities: row?.dominantEntities ?? existing?.dominantEntities,
              messages: [],
              updatedAt: ensuredMeta.updatedAt ?? row?.updatedAt ?? existing?.updatedAt ?? new Date().toISOString(),
            };
            const next = row
              ? prev.map((t) => (t.id === id ? { ...t, ...emptyThread! } : t))
              : [emptyThread, ...prev];
            threadsRef.current = next;
            return next;
          });
          return emptyThread;
        }

        let hydratedThread: ChatThread | null = null;
        setThreads((prev) => {
          const row = prev.find((t) => t.id === id);
          const updatedAt =
            ensuredMeta.updatedAt ??
            row?.updatedAt ??
            existing?.updatedAt ??
            messages[messages.length - 1].timestamp.toISOString();
          hydratedThread = {
            id,
            title: ensuredMeta.title || row?.title || existing?.title || 'Restored chat',
            subtitle: ensuredMeta.subtitle ?? row?.subtitle ?? existing?.subtitle,
            dominantEntities: row?.dominantEntities ?? existing?.dominantEntities,
            messages,
            updatedAt: row?.updatedAt && row.updatedAt > updatedAt ? row.updatedAt : updatedAt,
          };

          const next = row
            ? prev.map((t) => (t.id === id ? { ...t, ...hydratedThread! } : t))
            : [hydratedThread, ...prev];
          threadsRef.current = next;
          return next;
        });

        return hydratedThread;
      } catch (err: unknown) {
        const errMsg = err instanceof Error ? err.message : String(err);
        runtimeDiagnostics.record('backend_load_error', { threadId: id, meta: { op: 'hydrate_thread_messages', error: errMsg } });
        if (existing?.messages.length) return existing;
        return null;
      }
    },
    []
  );

  const switchThread = useCallback(
    (id: string) => {
      applyCurrentThreadId(id);
      if (isAuthenticated) {
        localStorage.setItem(lastThreadKey(userId), id);
      } else {
        persistLocal(threadsRef.current, id);
      }
    },
    [isAuthenticated, userId, persistLocal]
  );

  const updateThread = useCallback(
    (id: string, payload: {
      title?: string;
      /** subtitle is local-only — server persists it via the title service, not via this PATCH */
      subtitle?: string;
      dominantEntities?: string[];
      messages?: Message[];
      updatedAt?: string;
      /** Bump sidebar ordering — only on new message activity, never on open/hydrate sync */
      touchActivity?: boolean;
    }) => {
      const touchActivity = payload.touchActivity === true;
      const updatedAt = touchActivity
        ? (payload.updatedAt ?? new Date().toISOString())
        : undefined;
      let derivedTitle: string | undefined;
      if (payload.title === undefined && payload.messages !== undefined) {
        const current = threadsRef.current.find((t) => t.id === id);
        if (current && isGenericThreadTitle(current.title)) {
          derivedTitle = deriveTitleFromMessages(payload.messages) ?? undefined;
        }
      }
      const titleToApplyRaw = payload.title ?? derivedTitle;
      const titleToApply =
        titleToApplyRaw !== undefined
          ? ensureLocalUniqueTitle(titleToApplyRaw, id, threadsRef.current)
          : undefined;

      setThreads((prev) => {
        const next = prev.map((t) =>
          t.id === id
            ? {
                ...t,
                ...(titleToApply !== undefined && { title: titleToApply }),
                ...(payload.subtitle !== undefined && { subtitle: payload.subtitle }),
                ...(payload.dominantEntities !== undefined && { dominantEntities: payload.dominantEntities }),
                ...(payload.messages !== undefined && { messages: payload.messages }),
                ...(updatedAt !== undefined && { updatedAt }),
              }
            : t
        );
        const sorted = touchActivity ? sortThreadsByActivity(next) : next;
        threadsRef.current = sorted;
        if (!isAuthenticated) persistLocal(sorted, currentThreadIdRef.current);
        else if (userId) persistAuthThreadCache(userId, sorted, currentThreadIdRef.current);
        return sorted;
      });

      if (isAuthenticated && !isDemoChatMockup()) {
        if (payload.title !== undefined) {
          void store
            .dispatch(
              chatApi.endpoints.updateThread.initiate({
                threadId: id,
                body: { title: payload.title },
              })
            )
            .unwrap()
            .catch((err: unknown) => {
              const errMsg = mutationErrorMessage(err);
              runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'update_title', error: errMsg } });
            });
        } else if (derivedTitle) {
          void store
            .dispatch(chatApi.endpoints.patchThreadTitle.initiate({ threadId: id, title: derivedTitle }))
            .unwrap()
            .catch(() => {});
        }
        // subtitle is NOT sent here — server already persisted it via the title service
        if (touchActivity) {
          void store
            .dispatch(
              chatApi.endpoints.updateThread.initiate({
                threadId: id,
                body: { touchActivity: true },
              })
            )
            .unwrap()
            .catch((err: unknown) => {
              const errMsg = mutationErrorMessage(err);
              runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'touch_activity', error: errMsg } });
            });
        }
      }
    },
    [isAuthenticated, persistLocal]
  );

  /** Functional message update — avoids stale reads when multiple messages append in one turn. */
  const mutateThreadMessages = useCallback(
    (
      id: string,
      updater: (prev: Message[]) => Message[],
      opts?: { touchActivity?: boolean }
    ) => {
      const touchActivity = opts?.touchActivity === true;
      const updatedAt = touchActivity ? new Date().toISOString() : undefined;

      setThreads((prev) => {
        const row = prev.find((t) => t.id === id);
        if (!row) return prev;

        const messages = updater(row.messages);
        let derivedTitle: string | undefined;
        if (isGenericThreadTitle(row.title)) {
          derivedTitle = deriveTitleFromMessages(messages) ?? undefined;
        }
        const titleToApply =
          derivedTitle !== undefined
            ? ensureLocalUniqueTitle(derivedTitle, id, prev)
            : undefined;

        const next = prev.map((t) =>
          t.id === id
            ? {
                ...t,
                messages,
                ...(titleToApply !== undefined && { title: titleToApply }),
                ...(updatedAt !== undefined && { updatedAt }),
              }
            : t
        );
        const sorted = touchActivity ? sortThreadsByActivity(next) : next;
        threadsRef.current = sorted;
        if (!isAuthenticated) persistLocal(sorted, currentThreadIdRef.current);
        else if (userId) persistAuthThreadCache(userId, sorted, currentThreadIdRef.current);
        return sorted;
      });

      if (isAuthenticated && !isDemoChatMockup() && touchActivity) {
        void store
          .dispatch(
            chatApi.endpoints.updateThread.initiate({
              threadId: id,
              body: { touchActivity: true },
            })
          )
          .unwrap()
          .catch((err: unknown) => {
            const errMsg = mutationErrorMessage(err);
            runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'touch_activity', error: errMsg } });
          });
      }
    },
    [isAuthenticated, persistLocal]
  );

  /**
   * Rename a thread — optimistic local update + PATCH /threads/:id/title.
   * The title endpoint marks titleSource: 'user' so auto-generation is suppressed forever.
   */
  const renameThread = useCallback(
    (id: string, title: string) => {
      const trimmed = title.trim();
      if (!trimmed || isGenericThreadTitle(trimmed)) return;
      const unique = ensureLocalUniqueTitle(trimmed, id, threadsRef.current);
      setThreads((prev) =>
        prev.map((t) => (t.id === id ? { ...t, title: unique } : t))
      );
      if (isAuthenticated && !isDemoChatMockup()) {
        void store
          .dispatch(chatApi.endpoints.patchThreadTitle.initiate({ threadId: id, title: unique }))
          .unwrap()
          .catch((err: unknown) => {
            const errMsg = mutationErrorMessage(err);
            runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'rename_thread', error: errMsg } });
            if (!getBackendUnavailable() || !isBackendConnectionError(errMsg)) {
              dispatch(setThreadError(errMsg));
            }
            console.error('[useChatThreads] renameThread failed:', errMsg);
          });
      }
    },
    [isAuthenticated, dispatch]
  );

  const deleteThread = useCallback(
    (id: string) => {
      const removed = threadsRef.current.find((t) => t.id === id);
      setThreads((prev) => {
        const next = prev.filter((t) => t.id !== id);
        if (!isAuthenticated) persistLocal(next, currentThreadIdRef.current);
        else if (userId) persistAuthThreadCache(userId, next, currentThreadIdRef.current);
        return next;
      });
      if (currentThreadIdRef.current === id) {
        applyCurrentThreadId(null);
        if (isAuthenticated) localStorage.removeItem(lastThreadKey(userId));
      }
      threadPersistenceTracker.remove(id);
      if (isAuthenticated && !isDemoChatMockup()) {
        void store
          .dispatch(chatApi.endpoints.deleteThread.initiate(id))
          .unwrap()
          .catch((err: unknown) => {
            const errMsg = mutationErrorMessage(err);
            const status = mutationErrorStatus(err);
            if (status === 409 || errMsg.includes('409') || errMsg.includes('protected')) {
              runtimeDiagnostics.record('thread_delete_blocked', {
                threadId: id,
                meta: { reason: 'entity_linked', error: errMsg },
              });
              if (removed) {
                setThreads((prev) => {
                  if (prev.some((t) => t.id === id)) return prev;
                  const next = sortThreadsByActivity([removed, ...prev]);
                  threadsRef.current = next;
                  return next;
                });
              }
              return;
            }
            runtimeDiagnostics.record('save_error', { threadId: id, meta: { op: 'delete_thread', error: errMsg } });
            if (!getBackendUnavailable() || !isBackendConnectionError(errMsg)) {
              dispatch(setThreadError(errMsg));
            }
            console.error('[useChatThreads] deleteThread failed:', errMsg);
            if (removed) {
              setThreads((prev) => {
                if (prev.some((t) => t.id === id)) return prev;
                const next = sortThreadsByActivity([removed, ...prev]);
                threadsRef.current = next;
                return next;
              });
            }
          });
      }
    },
    [isAuthenticated, userId, persistLocal, dispatch]
  );

  const setCurrentThreadId = useCallback(
    (id: string | null) => {
      applyCurrentThreadId(id);
      if (isAuthenticated) {
        if (id) localStorage.setItem(lastThreadKey(userId), id);
        else localStorage.removeItem(lastThreadKey(userId));
        if (userId) persistAuthThreadCache(userId, threadsRef.current, id);
      } else {
        persistLocal(threadsRef.current, id);
      }
    },
    [isAuthenticated, userId, persistLocal, applyCurrentThreadId]
  );

  const dismissThreadError = useCallback(() => {
    dispatch(clearThreadError());
  }, [dispatch]);

  const loadThreads = useCallback(() => {
    if (isAuthenticated) return loadFromBackend();
    loadFromLocalStorage();
    return Promise.resolve();
  }, [isAuthenticated, loadFromBackend, loadFromLocalStorage]);

  return {
    threads,
    threadsLoading,
    threadsReady,
    threadsHasMore,
    threadsTotal,
    threadsLoadingMore,
    loadMoreThreads,
    currentThreadId,
    setCurrentThreadId,
    createThread,
    getThread,
    hydrateThreadMessages,
    switchThread,
    updateThread,
    mutateThreadMessages,
    renameThread,
    deleteThread,
    flushSave,
    loadThreads,
    lastError,
    dismissThreadError,
  };
};
