-- =====================================================
-- SYSTEM KNOWLEDGE — initial self-model seed
--
-- Grounds the SystemAgent so it can explain "how LoreBook understood this"
-- from real, verifiable facts about the codebase rather than hallucinating.
--
-- Idempotent: each row is inserted only if its concept is not already present,
-- so re-running the migration is safe.
-- =====================================================

INSERT INTO system_knowledge (concept, description, source_file, route, service_name, schema_name, confidence, last_verified_at)
SELECT v.concept, v.description, v.source_file, v.route, v.service_name, v.schema_name, v.confidence, now()
FROM (VALUES
  (
    'memory_ingestion_pipeline',
    'LoreBook memory ingestion is orchestrated by loreInterpretationPipeline.ts (lexer → parser → mapper).',
    'apps/server/src/services/pipeline/loreInterpretationPipeline.ts',
    '/api/meaning',
    'loreInterpretationPipeline',
    NULL,
    1.0
  ),
  (
    'lexical_analysis',
    'Raw signal extraction (entities, skills, emotions, events) is performed by lexicalAnalyzerService before meaning resolution.',
    'apps/server/src/services/lexical/lexicalAnalyzerService.ts',
    '/api/lexical',
    'lexicalAnalyzerService',
    NULL,
    1.0
  ),
  (
    'meaning_resolution',
    'Ambiguity, references, identity collisions, and contradictions are resolved by meaningResolutionService.',
    'apps/server/src/services/meaning/meaningResolutionService.ts',
    '/api/meaning',
    'meaningResolutionService',
    NULL,
    1.0
  ),
  (
    'entity_resolution',
    'Entity detection, deduplication, and linking are handled by entityResolutionService.',
    'apps/server/src/services/entityResolutionService.ts',
    '/api/entity-resolution',
    'entityResolutionService',
    'entities',
    1.0
  ),
  (
    'identity_collisions',
    'Identity collisions (same name claimed as self and a relationship) are detected by identityCollisionService and must never auto-merge.',
    'apps/server/src/services/meaning/identityCollisionService.ts',
    '/api/entity-authority',
    'identityCollisionService',
    NULL,
    1.0
  ),
  (
    'identity_corrections_audit',
    'Identity corrections and truth-state transitions are tracked through the cognition_mutations audit table via CorrectionAuthority.',
    'apps/server/src/services/provenance/CorrectionAuthority.ts',
    '/api/corrections',
    'correctionAuthority',
    'cognition_mutations',
    1.0
  ),
  (
    'memory_review_queue',
    'Proposed memories await user confirmation in the Memory Review Queue before becoming durable.',
    'apps/server/src/routes/memoryReviewQueue.ts',
    '/api/mrq',
    'memoryReviewQueue',
    NULL,
    1.0
  ),
  (
    'narrative_summaries',
    'Narrative summaries (themes, arcs, turning points) are generated by StoryOfSelfEngine.',
    'apps/server/src/services/storyOfSelf/storyOfSelfEngine.ts',
    '/api/story-of-self',
    'StoryOfSelfEngine',
    NULL,
    1.0
  ),
  (
    'what_ai_knows',
    'The WhatAIKnows page displays memories, insights, entities, and audit records the system holds about the user.',
    'apps/web/src/routes/WhatAIKnows.tsx',
    NULL,
    NULL,
    NULL,
    1.0
  ),
  (
    'agent_layer',
    'The System Cognition / Agent Layer runs after the interpretation pipeline; agents propose actions and never mutate core memory directly.',
    'apps/server/src/services/agents/loreAgentOrchestrator.ts',
    '/api/lore-agents',
    'loreAgentOrchestrator',
    'lore_agent_runs',
    1.0
  )
) AS v(concept, description, source_file, route, service_name, schema_name, confidence)
WHERE NOT EXISTS (
  SELECT 1 FROM system_knowledge sk WHERE sk.concept = v.concept
);
