/**
 * Separate intrinsic place identity from activities, visit context, stories, and source metadata.
 */

import { classifyTagBucket } from '../../locations/placePresenceSemantics';
import { emptyTagGroups, type PlaceTagGroups } from './placeMigrationTypes';

const SOURCE_META_TAGS = new Set([
  'x-import',
  'x_import',
  'twitter',
  'post',
  'registry',
  'chat_detect',
  'chat-detect',
  'auto_generated',
  'autogenerated',
  'media',
  'import',
]);

const ACTIVITY_TAGS = new Set([
  'dancing',
  'dance',
  'running',
  'studying',
  'drinking',
  'coding',
  'gaming',
  'workout',
  'fitness',
]);

const INTRINSIC_HINTS = new Set([
  'nightclub',
  'music venue',
  'park',
  'university',
  'city',
  'district',
  'country',
  'private residence',
  'home',
  'event space',
  'diy venue',
  'pool hall',
  'los angeles',
]);

function normalizeTag(tag: string): string {
  return (tag ?? '')
    .toLowerCase()
    .replace(/[’‘]/g, "'")
    .replace(/[_-]+/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export type TagSanitizeResult = {
  groups: PlaceTagGroups;
  removedTags: string[];
  retainedTags: string[];
  movedTags: string[];
};

/**
 * Rebuild tag groups from an arbitrary bag of tags / place_tags / story tags.
 */
export function sanitizePlaceTags(
  tags: string[],
  opts?: { placeType?: string | null; preferredIntrinsic?: string[] },
): TagSanitizeResult {
  const groups = emptyTagGroups();
  const removedTags: string[] = [];
  const retainedTags: string[] = [];
  const movedTags: string[] = [];
  const seen = new Set<string>();

  for (const raw of tags) {
    const tag = (raw ?? '').trim();
    if (!tag) continue;
    const key = normalizeTag(tag);
    if (!key || seen.has(key)) continue;
    seen.add(key);

    if (SOURCE_META_TAGS.has(key) || SOURCE_META_TAGS.has(key.replace(/\s+/g, '_'))) {
      groups.importedSourceTags.push(tag);
      movedTags.push(`${tag}→importedSourceTags`);
      removedTags.push(tag);
      continue;
    }

    if (ACTIVITY_TAGS.has(key) || key === 'dancing') {
      groups.activityTags.push(tag);
      movedTags.push(`${tag}→activityTags`);
      continue;
    }

    if (INTRINSIC_HINTS.has(key)) {
      groups.intrinsicTags.push(tag);
      retainedTags.push(tag);
      continue;
    }

    const bucket = classifyTagBucket(tag);
    if (bucket === 'story') {
      groups.storyAssociationTags.push(tag);
      movedTags.push(`${tag}→storyAssociationTags`);
      removedTags.push(tag);
      continue;
    }
    if (bucket === 'visit_context') {
      groups.visitContextTags.push(tag);
      movedTags.push(`${tag}→visitContextTags`);
      continue;
    }

    groups.visitContextTags.push(tag);
    movedTags.push(`${tag}→visitContextTags`);
  }

  for (const intrinsic of opts?.preferredIntrinsic ?? []) {
    const key = normalizeTag(intrinsic);
    if (!key || groups.intrinsicTags.some((t) => normalizeTag(t) === key)) continue;
    groups.intrinsicTags.push(intrinsic);
    retainedTags.push(intrinsic);
  }

  if (opts?.placeType) {
    const typeTag = normalizeTag(opts.placeType).replace(/_/g, ' ');
    if (typeTag && !groups.intrinsicTags.some((t) => normalizeTag(t) === typeTag)) {
      groups.intrinsicTags.push(typeTag);
      retainedTags.push(typeTag);
    }
  }

  return { groups, removedTags, retainedTags, movedTags };
}
