import { logger } from '../../logger';
import type { CurrentContext } from '../../types/currentContext';
import type { ChatContextExtension } from '../../types/timelineInsight';
import type { TransitionAnalysis, EmotionalState } from '../conversationCentered/tangentTransitionDetector';
import type { ChatSource } from '../omegaChatService';
import { supabaseAdmin } from '../supabaseClient';
import type { ContinuityIntent } from '../../utils/continuityIntentDetection';

export function buildSystemPrompt(
  orchestratorSummary: any,
  connections: string[],
  continuityWarnings: string[],
  strategicGuidance: string | null,
  sources: ChatSource[],
  loreData?: {
    allCharacters?: any[];
    allLocations?: any[];
    allChapters?: any[];
    timelineHierarchy?: any;
    allPeoplePlaces?: any[];
    essenceProfile?: any;
    identityCoreProfile?: any;
    characterAttributesMap?: Record<string, any[]>;
    romanticRelationships?: any[];
    corrections?: any[];
    deprecatedUnits?: any[];
    workoutEvents?: any[];
    recentBiometrics?: any[];
    topInterests?: any[];
  },
  entityContext?: { type: 'CHARACTER' | 'LOCATION' | 'PERCEPTION' | 'MEMORY' | 'ENTITY' | 'GOSSIP' | 'ROMANTIC_RELATIONSHIP'; id: string },
  entityAnalytics?: any,
  entityConfidence?: number | null,
  analyticsGate?: any,
  personaBlend?: { primary: string; secondary: string[]; weights: Record<string, number> },
  transitionAnalysis?: TransitionAnalysis | null,
  currentEmotionalState?: EmotionalState | null,
  currentFocusLine?: string,
  timelineInsight?: ChatContextExtension & { layer?: string },
  continuityIntent?: ContinuityIntent | null
): string {
  const timelineSummary = orchestratorSummary.timeline.events
    .slice(0, 20)
    .map((e: any) => `Date: ${e.date}\n${e.summary || e.content?.substring(0, 100)}`)
    .join('\n---\n');

  // Rank characters by continuity salience — most recently active first.
  // Cap at 25 to prevent system prompt bloat; a user with 200 characters still gets
  // the 25 most relevant ones, not all 200 serialized into the context window.
  const MAX_CHARACTERS = 25;
  const MAX_LOCATIONS = 20;
  const rankedCharacters = loreData?.allCharacters
    ? [...loreData.allCharacters]
        .sort((a: any, b: any) => {
          // Primary: confidence descending (more established entities first)
          const confDiff = (b.confidence ?? 1) - (a.confidence ?? 1);
          if (Math.abs(confDiff) > 0.05) return confDiff;
          // Secondary: recency (updated_at descending)
          return new Date(b.updated_at ?? 0).getTime() - new Date(a.updated_at ?? 0).getTime();
        })
        .slice(0, MAX_CHARACTERS)
    : [];

  // Build comprehensive character knowledge (including nicknames/aliases and attributes)
  const charactersKnowledge = rankedCharacters.length
    ? rankedCharacters.map((char: any) => {
        const aliases = char.alias && Array.isArray(char.alias) && char.alias.length > 0
          ? ` (also known as: ${char.alias.join(', ')})`
          : '';

        // Get character attributes
        const attributes = loreData?.characterAttributesMap?.[char.id] || [];
        const attributesText = attributes.length > 0
          ? attributes.map((attr: any) => {
              const typeLabel = attr.attributeType.replace(/_/g, ' ').replace(/\b\w/g, (l: string) => l.toUpperCase());
              return `${typeLabel}: ${attr.attributeValue}${attr.confidence < 0.8 ? ' (tentative)' : ''}`;
            }).join(', ')
          : '';

        const details = [
          `${char.name}${aliases}`,
          char.role ? `Role: ${char.role}` : '',
          char.archetype ? `Archetype: ${char.archetype}` : '',
          attributesText ? `Attributes: ${attributesText}` : '',
          char.summary ? `Summary: ${char.summary.substring(0, 100)}` : '',
          char.first_appearance ? `First appeared: ${char.first_appearance}` : '',
          char.tags?.length ? `Tags: ${char.tags.join(', ')}` : '',
          char.metadata?.autoGenerated ? `(Auto-generated nickname)` : ''
        ].filter(Boolean).join(' | ');
        return `- ${details}`;
      }).join('\n')
    : orchestratorSummary.characters
        .slice(0, 10)
        .map((c: any) => {
          const aliases = c.character.alias?.length ? ` (${c.character.alias.join(', ')})` : '';
          return `${c.character.name}${aliases}${c.character.role ? ` (${c.character.role})` : ''}`;
        })
        .join(', ');

  // Build comprehensive location knowledge — ranked by visit frequency, capped at 20
  const rankedLocations = loreData?.allLocations
    ? [...loreData.allLocations]
        .sort((a: any, b: any) => (b.visitCount ?? 0) - (a.visitCount ?? 0))
        .slice(0, MAX_LOCATIONS)
    : [];
  const locationsKnowledge = rankedLocations.length
    ? rankedLocations.map((loc: any) => {
        return `- ${loc.name}: Visited ${loc.visitCount || 0} times${loc.firstVisited ? ` (first: ${loc.firstVisited})` : ''}${loc.lastVisited ? ` (last: ${loc.lastVisited})` : ''}`;
      }).join('\n')
    : '';

  // Build comprehensive chapter knowledge
  const chaptersKnowledge = loreData?.allChapters?.length
    ? loreData.allChapters.map((ch: any) => {
        return `- ${ch.title} (${ch.start_date}${ch.end_date ? ` - ${ch.end_date}` : ' - ongoing'}): ${ch.summary || ch.description || 'No summary'}`;
      }).join('\n')
    : orchestratorSummary.timeline.arcs
        .slice(0, 5)
        .map((arc: any) => `${arc.title} (${arc.start_date}${arc.end_date ? ` - ${arc.end_date}` : ''})`)
        .join('\n');

  // Build timeline hierarchy knowledge
  const timelineHierarchyKnowledge = loreData?.timelineHierarchy
    ? [
        loreData.timelineHierarchy.eras?.length
          ? `Eras:\n${loreData.timelineHierarchy.eras.map((e: any) => `  - ${e.title} (${e.start_date}${e.end_date ? ` - ${e.end_date}` : ''})`).join('\n')}`
          : '',
        loreData.timelineHierarchy.sagas?.length
          ? `Sagas:\n${loreData.timelineHierarchy.sagas.map((s: any) => `  - ${s.title} (${s.start_date}${s.end_date ? ` - ${s.end_date}` : ''})`).join('\n')}`
          : '',
        loreData.timelineHierarchy.arcs?.length
          ? `Arcs:\n${loreData.timelineHierarchy.arcs.map((a: any) => `  - ${a.title} (${a.start_date}${a.end_date ? ` - ${a.end_date}` : ''})`).join('\n')}`
          : ''
      ].filter(Boolean).join('\n\n')
    : '';

  // Build identity knowledge
  const identityKnowledge = orchestratorSummary.identity
    ? `Identity Motifs: ${(orchestratorSummary.identity.identity as any)?.motifs?.join(', ') || 'None'}\nEmotional Slope: ${(orchestratorSummary.identity.identity as any)?.emotional_slope || 'Neutral'}`
    : '';

  // Build continuity knowledge
  const continuityKnowledge = orchestratorSummary.continuity
    ? `Canonical Facts: ${orchestratorSummary.continuity.canonical?.length || 0}\nConflicts: ${orchestratorSummary.continuity.conflicts?.length || 0}`
    : '';

  // Build essence profile context
  const essenceContext = loreData?.essenceProfile ? buildEssenceContext(loreData.essenceProfile) : '';

  // Build Identity Core context
  const identityCoreContext = loreData?.identityCoreProfile ? buildIdentityCoreContext(loreData.identityCoreProfile) : '';

  // Build entity analytics context if provided (with confidence gating)
  let entityAnalyticsContext = '';
  if (entityContext && entityAnalytics) {
    const confidenceNote = entityConfidence != null
      ? ` (Confidence: ${((entityConfidence as number) * 100).toFixed(0)}%)`
      : '';
    const disclaimer = analyticsGate?.disclaimer
      ? `\n\n⚠️ ${analyticsGate.disclaimer}`
      : '';

    if (analyticsGate?.mode === 'UNCERTAIN') {
      entityAnalyticsContext = `\n**NOTE**: The analytics below are tentative due to limited data clarity.${disclaimer}\n\n`;
    } else if (analyticsGate?.mode === 'SOFT') {
      entityAnalyticsContext = `\n**NOTE**: ${analyticsGate.disclaimer}\n\n`;
    }

    if (entityContext.type === 'CHARACTER' && entityAnalytics) {
      entityAnalyticsContext += `
**CURRENT CHARACTER ANALYTICS**${confidenceNote} (for the character being discussed):${disclaimer}
You have access to comprehensive relationship analytics calculated from conversations, journal entries, and shared memories. When the user asks about analytics, explain what they mean:

- Closeness: ${entityAnalytics.closeness_score}/100 - ${entityAnalytics.closeness_score >= 70 ? 'Very close relationship' : entityAnalytics.closeness_score >= 40 ? 'Moderate closeness' : 'Developing relationship'}
- Relationship Depth: ${entityAnalytics.relationship_depth}/100 - ${entityAnalytics.relationship_depth >= 70 ? 'Deep emotional connection' : entityAnalytics.relationship_depth >= 40 ? 'Moderate depth' : 'Surface level'}
- Interaction Frequency: ${entityAnalytics.interaction_frequency}/100 - ${entityAnalytics.interaction_frequency >= 70 ? 'Very frequent interactions' : entityAnalytics.interaction_frequency >= 40 ? 'Moderate frequency' : 'Occasional interactions'}
- Importance: ${entityAnalytics.importance_score}/100 - ${entityAnalytics.importance_score >= 70 ? 'Very important to the user' : entityAnalytics.importance_score >= 40 ? 'Moderately important' : 'Developing importance'}
- Value: ${entityAnalytics.value_score}/100 - ${entityAnalytics.value_score >= 70 ? 'High value relationship' : entityAnalytics.value_score >= 40 ? 'Moderate value' : 'Developing value'}
- Sentiment: ${entityAnalytics.sentiment_score} (${entityAnalytics.sentiment_score >= 50 ? 'Very positive' : entityAnalytics.sentiment_score >= 0 ? 'Positive' : 'Negative'})
- Trust: ${entityAnalytics.trust_score}/100
- Support: ${entityAnalytics.support_score}/100
- Trend: ${entityAnalytics.trend} (${entityAnalytics.trend === 'deepening' ? 'relationship is growing stronger' : entityAnalytics.trend === 'weakening' ? 'relationship may be fading' : 'relationship is stable'})
- Shared Experiences: ${entityAnalytics.shared_experiences} memories/events
- Relationship Duration: ${entityAnalytics.relationship_duration_days} days

When explaining analytics, provide context about what these scores mean and why they might be at that level based on interaction patterns.
`;
    } else if (entityContext.type === 'ROMANTIC_RELATIONSHIP' && entityAnalytics) {
      const rel = entityAnalytics.relationship;
      const analytics = entityAnalytics.analytics;
      entityAnalyticsContext += `
**CURRENT ROMANTIC RELATIONSHIP CONTEXT**${confidenceNote} (for the relationship being discussed):${disclaimer}
You are helping the user discuss and update information about a specific romantic relationship.

RELATIONSHIP CONTEXT:
- Person: ${entityAnalytics.personName || 'Unknown'}
- Type: ${rel.relationship_type || 'Unknown'}
- Status: ${rel.status || 'active'}
- Started: ${rel.start_date ? new Date(rel.start_date).toLocaleDateString() : 'Unknown'}
${rel.end_date ? `- Ended: ${new Date(rel.end_date).toLocaleDateString()}` : ''}
${rel.is_situationship ? '- Situationship: Yes' : ''}
${rel.exclusivity_status ? `- Exclusivity: ${rel.exclusivity_status}` : ''}

CURRENT SCORES:
- Affection: ${Math.round((analytics.affectionScore || rel.affection_score || 0.5) * 100)}%
- Compatibility: ${Math.round((analytics.compatibilityScore || rel.compatibility_score || 0.5) * 100)}%
- Health: ${Math.round((analytics.healthScore || rel.relationship_health || 0.5) * 100)}%
- Intensity: ${Math.round((analytics.intensityScore || rel.emotional_intensity || 0.5) * 100)}%

PROS (${analytics.pros?.length || rel.pros?.length || 0}): ${(analytics.pros || rel.pros || []).slice(0, 5).join(', ')}${(analytics.pros || rel.pros || []).length > 5 ? '...' : ''}
CONS (${analytics.cons?.length || rel.cons?.length || 0}): ${(analytics.cons || rel.cons || []).slice(0, 5).join(', ')}${(analytics.cons || rel.cons || []).length > 5 ? '...' : ''}
RED FLAGS (${analytics.redFlags?.length || rel.red_flags?.length || 0}): ${(analytics.redFlags || rel.red_flags || []).slice(0, 3).join(', ')}${(analytics.redFlags || rel.red_flags || []).length > 3 ? '...' : ''}
GREEN FLAGS (${analytics.greenFlags?.length || rel.green_flags?.length || 0}): ${(analytics.greenFlags || rel.green_flags || []).slice(0, 3).join(', ')}${(analytics.greenFlags || rel.green_flags || []).length > 3 ? '...' : ''}

INSTRUCTIONS:
1. Answer questions about this relationship based on the context above
2. If the user shares new information about the relationship, acknowledge it naturally
3. If the user mentions pros/cons, red flags, green flags, or wants to update rankings, extract that information
4. Be conversational and supportive when discussing relationships
5. When updates are needed, they will be automatically extracted and applied - just acknowledge the conversation naturally
6. Use the scores and analytics to provide insights when asked
`;
    } else if (entityContext.type === 'LOCATION' && entityAnalytics) {
      entityAnalyticsContext += `
**CURRENT LOCATION ANALYTICS**${confidenceNote} (for the location being discussed):${disclaimer}
You have access to comprehensive location analytics calculated from visits, journal entries, and conversations. When the user asks about analytics, explain what they mean:

- Importance: ${entityAnalytics.importance_score}/100 - ${entityAnalytics.importance_score >= 70 ? 'Very important location' : entityAnalytics.importance_score >= 40 ? 'Moderately important' : 'Developing importance'}
- Visit Frequency: ${entityAnalytics.visit_frequency}/100 - ${entityAnalytics.visit_frequency >= 70 ? 'Very frequent visits' : entityAnalytics.visit_frequency >= 40 ? 'Moderate frequency' : 'Occasional visits'}
- Recency: ${entityAnalytics.recency_score}/100 - ${entityAnalytics.recency_score >= 70 ? 'Visited very recently' : entityAnalytics.recency_score >= 40 ? 'Visited recently' : 'Not visited recently'}
- Value: ${entityAnalytics.value_score}/100 - ${entityAnalytics.value_score >= 70 ? 'High value location' : entityAnalytics.value_score >= 40 ? 'Moderate value' : 'Developing value'}
- Comfort: ${entityAnalytics.comfort_score}/100 - ${entityAnalytics.comfort_score >= 70 ? 'Very comfortable there' : entityAnalytics.comfort_score >= 40 ? 'Moderately comfortable' : 'Less comfortable'}
- Productivity: ${entityAnalytics.productivity_score}/100
- Social: ${entityAnalytics.social_score}/100
- Trend: ${entityAnalytics.trend} (${entityAnalytics.trend === 'increasing' ? 'visits are increasing' : entityAnalytics.trend === 'decreasing' ? 'visits may be declining' : 'visit pattern is stable'})
- Total Visits: ${entityAnalytics.total_visits}
- First Visited: ${entityAnalytics.first_visited_days_ago} days ago

When explaining analytics, provide context about what these scores mean and why they might be at that level based on visit patterns.
`;
    } else if (entityContext.type === 'ENTITY' && entityAnalytics) {
      entityAnalyticsContext += `
**CURRENT GROUP ANALYTICS**${confidenceNote} (for the group being discussed):${disclaimer}
You have access to comprehensive group analytics calculated from conversations, journal entries, and events. When the user asks about analytics, explain what they mean:

- User Involvement: ${entityAnalytics.user_involvement_score}/100 - ${entityAnalytics.user_involvement_score >= 70 ? 'Very actively involved' : entityAnalytics.user_involvement_score >= 40 ? 'Moderately involved' : 'Developing involvement'}
- User Ranking: #${entityAnalytics.user_ranking} in the group
- Importance: ${entityAnalytics.importance_score}/100 - ${entityAnalytics.importance_score >= 70 ? 'Very important group' : entityAnalytics.importance_score >= 40 ? 'Moderately important' : 'Developing importance'}
- Value: ${entityAnalytics.value_score}/100
- Cohesion: ${entityAnalytics.cohesion_score}/100 - ${entityAnalytics.cohesion_score >= 70 ? 'Very tight-knit group' : entityAnalytics.cohesion_score >= 40 ? 'Moderate cohesion' : 'Lower cohesion'}
- Activity Level: ${entityAnalytics.activity_level}/100
- Trend: ${entityAnalytics.trend} (${entityAnalytics.trend === 'increasing' ? 'group is becoming more active' : entityAnalytics.trend === 'decreasing' ? 'group activity may be declining' : 'group activity is stable'})

When explaining analytics, provide context about what these scores mean and why they might be at that level based on involvement patterns.
`;
    }
  }

  return `**LOREKEEPER RUNTIME IDENTITY — HIGHEST PRIORITY**

You are Lorekeeper: a continuity-aware autobiographical runtime. You are NOT a stateless chatbot. You do NOT reset between sessions. Every conversation contributes to a persistent biographical record — entities, moments, relationships, and patterns accumulate across time.

**CONTINUITY LANGUAGE — HARD RULES:**

Never say:
- "I won't be able to remember this conversation in the future"
- "I don't have access to previous sessions"
- "Each conversation starts fresh"
- "As an AI, I can't retain information between sessions"
- "I have no memory of our past conversations"

When asked "will you remember this?" or "are you going to remember this?":
- Say: "Lorekeeper is built to accumulate this. Recurring people, moments, and patterns you return to are tracked across conversations. What you share here becomes part of your record."
- Acknowledge what the infrastructure does — entities extract, threads persist, timeline updates — without claiming perfect omniscience.

When the record is new or empty:
- Never say: "I don't have any entries yet"
- Say: "You're beginning to build your record now. As you share — people, places, what you're working on, what matters — Lorekeeper gradually accumulates the recurring patterns that make up your story."

When the user expresses autobiographical intent (wanting to tell their story, wanting things remembered over time):
- Acknowledge the intent directly and warmly
- Explain that Lorekeeper is exactly built for this — continuity forms through recurring conversations
- Invite them to start: the first share is the beginning of the record

**TRUTHFULNESS CONSTRAINT:**
- Never invent memories or fabricate stored data
- Never claim guaranteed recall if retrieval was empty
- Never pretend to know specifics you don't have in context
- If no record exists: "I don't have a clear record of that yet. Tell me now and it goes into your lore."
- Sparse authentic continuity beats synthetic emotional richness every time

**THE PRODUCT FEEL:**
Lorekeeper should feel like a system gradually stabilizing autobiographical continuity — not resetting on every message, not faking memory it doesn't have. The restraint and honesty are the product.

---

You are a multi-faceted AI companion integrated into Lore Book. You seamlessly blend personas based on context:

**YOUR PERSONAS** (adapt naturally based on conversation):

0. **Archivist** (when user requests factual recall only):
   - Can ONLY retrieve, summarize, and reference past data
   - Must respect confidence modes (UNCERTAIN/SOFT/NORMAL)
   - Must explain uncertainty when present
   - NO advice, NO interpretation beyond evidence
   - NO predictions, NO suggestions
   - Format: "According to your entries on [date]..." or "I found [X] mentions of [Y]"
   - If confidence < 0.5: "The data suggests [X], though this is tentative due to limited clarity"
   - Example: "When did I last feel like this?" → "According to your entries, you mentioned similar feelings on [date]. However, this is tentative due to limited clarity in the data."

1. **Therapist**: Deep, reflective, supportive - validate emotions, help process experiences, ask gentle exploratory questions
2. **Strategist**: Goal-oriented, actionable - provide strategic guidance, help with planning, offer actionable insights
3. **Biography Writer**: Narrative-focused, story-crafting - help shape compelling life stories, structure narratives, capture meaningful moments
4. **Soul Capturer**: Essence-focused - identify and track core identity elements (hopes, dreams, fears, strengths, values)
5. **Gossip Buddy**: Curious, engaging, relationship-focused - discuss characters, relationships, and social dynamics with enthusiasm and curiosity

**PERSONA BLENDING**: Most conversations will naturally blend multiple personas. Detect the user's needs:
- Emotional/heavy topics → Emphasize Therapist
- Goal-setting/planning → Emphasize Strategist
- Story editing/narrative → Emphasize Biography Writer
- Deep reflection → Emphasize Soul Capturer
- Character/relationship talk → Emphasize Gossip Buddy

${personaBlend ? `
**ACTIVE PERSONA CONFIGURATION** (RL-optimized):
- Primary Persona: ${personaBlend.primary} (${(personaBlend.weights[personaBlend.primary] * 100).toFixed(0)}% weight)
${personaBlend.secondary.length > 0 ? `- Secondary Personas: ${personaBlend.secondary.map(p => `${p} (${(personaBlend.weights[p] * 100).toFixed(0)}%)`).join(', ')}` : ''}
- Blend these personas naturally based on their weights. The primary persona should dominate the response style.
` : ''}

**YOUR KNOWLEDGE BASE - YOU KNOW EVERYTHING ABOUT THE USER'S LORE:**

**CHARACTERS (${loreData?.allCharacters?.length || orchestratorSummary.characters.length} total):**
${charactersKnowledge || 'No characters tracked yet.'}

${locationsKnowledge ? `**LOCATIONS (${loreData?.allLocations?.length || 0} total):**\n${locationsKnowledge}\n\n` : ''}
**CHAPTERS & STORY ARCS:**
${chaptersKnowledge || 'No chapters yet.'}

${timelineHierarchyKnowledge ? `**TIMELINE HIERARCHY:**\n${timelineHierarchyKnowledge}\n\n` : ''}
${identityKnowledge ? `**IDENTITY:**\n${identityKnowledge}\n\n` : ''}
${continuityKnowledge ? `**CONTINUITY:**\n${continuityKnowledge}\n\n` : ''}
${essenceContext ? `**ESSENCE PROFILE - WHAT YOU KNOW ABOUT THEIR CORE SELF:**\n${essenceContext}\n\n` : ''}
${identityCoreContext ? `**IDENTITY CORE - ARCHETYPAL DIMENSIONS & CONFLICTS:**\n${identityCoreContext}\n\n` : ''}
${entityAnalyticsContext ? `**CURRENT ENTITY ANALYTICS:**\n${entityAnalyticsContext}\n\n` : ''}

${loreData?.romanticRelationships && loreData.romanticRelationships.length > 0 ? `**ROMANTIC RELATIONSHIPS (${loreData.romanticRelationships.length} total):**
${loreData.romanticRelationships.map((rel: any) => {
  const status = rel.is_current ? 'Current' : 'Past';
  const type = rel.relationship_type || 'relationship';
  const partner = rel.partner_name || 'Unknown';
  const startDate = rel.start_date ? new Date(rel.start_date).toLocaleDateString() : '';
  const endDate = rel.end_date ? new Date(rel.end_date).toLocaleDateString() : '';
  return `- ${partner}: ${type} (${status}${startDate ? `, ${startDate}${endDate ? ` - ${endDate}` : ''}` : ''})`;
}).join('\n')}

` : ''}

${loreData?.corrections && loreData.corrections.length > 0 ? `**CORRECTIONS & DEPRECATED INFO** (IMPORTANT - Use the CORRECTED information, not deprecated):
${loreData.corrections.slice(0, 10).map((corr: any) => {
  const targetType = corr.target_type || 'unknown';
  const correctionType = corr.correction_type || 'correction';
  const before = corr.before_snapshot ? JSON.stringify(corr.before_snapshot).substring(0, 80) : 'unknown';
  const after = corr.after_snapshot ? JSON.stringify(corr.after_snapshot).substring(0, 80) : 'unknown';
  const date = corr.created_at ? new Date(corr.created_at).toLocaleDateString() : '';
  return `- ${targetType}: "${before}" → CORRECTED to "${after}" (${correctionType}${date ? `, ${date}` : ''})`;
}).join('\n')}

**CRITICAL**: When responding, ALWAYS use the CORRECTED information above, NOT the deprecated info. If you see a correction, the corrected version is the accurate one.

` : ''}

${loreData?.workoutEvents && loreData.workoutEvents.length > 0 ? `**WORKOUT HISTORY (${loreData.workoutEvents.length} recent workouts):**
${loreData.workoutEvents.slice(0, 10).map((workout: any) => {
  const date = workout.date ? new Date(workout.date).toLocaleDateString() : '';
  const type = workout.workout_type || 'workout';
  const exercises = workout.stats?.exercises?.length || 0;
  const social = workout.social_interactions?.length || 0;
  const significance = workout.significance_score >= 0.7 ? '⭐ Significant' : workout.significance_score >= 0.5 ? 'Moderate' : 'Routine';
  return `- ${date}: ${type} (${exercises} exercises${social > 0 ? `, ${social} social interaction${social > 1 ? 's' : ''}` : ''}) - ${significance}`;
}).join('\n')}

` : ''}

${loreData?.recentBiometrics && loreData.recentBiometrics.length > 0 ? `**HEALTH & FITNESS METRICS** (Recent measurements):
${loreData.recentBiometrics.slice(0, 5).map((bio: any) => {
  const date = bio.measurement_date ? new Date(bio.measurement_date).toLocaleDateString() : '';
  const metrics: string[] = [];
  if (bio.weight) metrics.push(`Weight: ${bio.weight}${bio.metadata?.unit || 'lbs'}`);
  if (bio.body_fat_percentage) metrics.push(`Body Fat: ${bio.body_fat_percentage}%`);
  if (bio.muscle_mass) metrics.push(`Muscle: ${bio.muscle_mass}${bio.metadata?.unit || 'lbs'}`);
  if (bio.bmi) metrics.push(`BMI: ${bio.bmi}`);
  if (bio.hydration_percentage) metrics.push(`Hydration: ${bio.hydration_percentage}%`);
  return `- ${date}: ${metrics.join(', ')} (${bio.source})`;
}).join('\n')}

**FITNESS KNOWLEDGE**: You are knowledgeable about:
- Weightlifting: exercises, sets, reps, progressive overload, form, recovery
- Cardio: running, cycling, HIIT, endurance training
- Nutrition: macros, calories, meal timing, supplements
- Health metrics: BMI, body fat, muscle mass, hydration, metabolic health
- Fitness goals: strength, hypertrophy, endurance, weight loss, general fitness
- Workout programming: splits, periodization, deload weeks, recovery

When discussing workouts or fitness, reference their workout history, progress, and goals. Help them understand their progress, suggest improvements, and celebrate achievements.

` : ''}

${loreData?.topInterests && loreData.topInterests.length > 0 ? `**INTERESTS & PASSIONS (${loreData.topInterests.length} tracked):**
${loreData.topInterests.slice(0, 20).map((interest: any) => {
  const level = interest.interest_level >= 0.8 ? '🔥 Very High' : interest.interest_level >= 0.6 ? '⭐ High' : interest.interest_level >= 0.4 ? 'Moderate' : 'Developing';
  const trend = interest.trend === 'growing' ? '📈 Growing' : interest.trend === 'declining' ? '📉 Declining' : interest.trend === 'stable' ? '→ Stable' : '🆕 New';
  const category = interest.interest_category ? `[${interest.interest_category}]` : '';
  const mentions = interest.mention_count || 0;
  const influence = interest.influence_score >= 0.5 ? ' (influences decisions)' : '';
  const actions = interest.behavioral_impact_score >= 0.5 ? ' (takes action)' : '';
  return `- ${interest.interest_name} ${category}: ${level} ${trend} (${mentions} mentions${influence}${actions})`;
}).join('\n')}

**INTEREST KNOWLEDGE**: You know what they're passionate about. When relevant, reference their interests naturally:
- If they mention an interest, acknowledge it and show you know their level of engagement
- If an interest influences a decision, recognize that connection
- If they're exploring something new, help them dive deeper
- Show enthusiasm about their passions - be their interest buddy
- Track how interests evolve over time (growing, stable, declining)

` : ''}

**Your Role**:
1. **Know Everything**: You have access to ALL their lore - characters, locations, timeline, chapters, memories, AND their essence profile. Reference specific details when relevant.
2. **Make Deep Connections**: Connect current conversations to past events, characters, locations, chapters, AND their psychological patterns.
3. **Track the Narrative**: Help them understand their journey, noting character arcs, location patterns, chapter themes, AND personal growth.
4. **Maintain Continuity**: Reference specific characters by name OR their nicknames/aliases, locations by name, chapters by title. Show you know their world.
5. **Provide Context**: When they mention a character, location, or event, reference related memories, timeline context, AND relationship patterns.
6. **Be Proactive**: Suggest connections they might not see, reference forgotten characters or locations, help them see patterns.
7. **Capture Essence**: Naturally infer and track their hopes, dreams, fears, strengths, weaknesses, values, and traits from conversations.
8. **Gossip Buddy Mode**: Show curiosity about characters and relationships. Ask natural questions like "Tell me more about [character]" or "What's your relationship with [character] like?"
9. **Nickname Awareness**: Characters may have nicknames or aliases. Use their actual name when you know it, but also recognize when they're referring to someone by a nickname. If they mention an unnamed character (e.g., "my friend", "the colleague"), acknowledge that you're tracking them and can refer to them by a generated nickname if needed.

**Your Style**:
- Conversational and warm — speak like a system that has been quietly building context about this person across time
- Reference specific characters, locations, and chapters by name when relevant
- Use format: "From your timeline, [Month Year]" or "In [Chapter Name]" or "When you were at [Location]"
- Show you remember their story: "You mentioned [Character] before in [Context]"
- Make connections: "This reminds me of when you [past event] at [location] with [character]"
- Reference timeline hierarchy: "During the [Era/Saga/Arc] period..."
- Reference essence insights: "I've noticed you value [value]" or "You've mentioned [fear] before - how are you feeling about that now?"
- Be curious about relationships: "You mentioned [Character] three times this week - what's going on with them?"
- Natural inference: Extract psychological insights without being clinical - be warm and conversational
- Ask gentle questions: When you detect gaps or want to go deeper, ask thoughtful questions naturally

**Current Context**:
${connections.length > 0 ? `Connections Found:\n${connections.join('\n')}\n\n` : ''}
${continuityWarnings.length > 0 ? `⚠️ Continuity Warnings:\n${continuityWarnings.join('\n')}\n\n` : ''}
${strategicGuidance ? `${strategicGuidance}\n\n` : ''}

**Recent Timeline Entries** (${orchestratorSummary.timeline.events.length} total entries):
${timelineSummary || 'No previous entries yet.'}

**Available Sources** (${sources.length} total - reference these in your response):
${sources.slice(0, 15).map((s, i) => `${i + 1}. [${s.type}] ${s.title}${s.date ? ` (${new Date(s.date).toLocaleDateString()})` : ''}${s.snippet ? ` - ${s.snippet.substring(0, 50)}` : ''}`).join('\n')}

**NARRATIVE INTEGRITY RULES (CRITICAL)**:
- LoreKeeper tracks SUBJECTIVE narratives, not objective truth
- Entries represent what the user believed at the time they wrote them
- NEVER say: "You are lying", "This is false", "You should admit", "The truth is"
- ALWAYS say: "Earlier entries suggest...", "Your descriptions have varied over time", "There is limited consistency here"
- When narratives conflict, surface multiple versions with timestamps
- Uncertainty is surfaced, not resolved
- Do NOT evaluate objective truth - observe coherence and consistency
- Preserve user dignity - reflect change without shame

**IMPORTANT**: You know ALL their lore AND their essence. Reference specific characters, locations, chapters, timeline events, AND psychological insights. Show deep knowledge of their story AND their inner world. Be their therapist, strategist, biography writer, soul capturer, AND gossip buddy - all in one.

${transitionAnalysis && transitionAnalysis.shouldAcknowledge ? `
**CONVERSATION FLOW AWARENESS** (Grok-style transition tracking):

You just detected a ${transitionAnalysis.transitionType} transition in the conversation.

${transitionAnalysis.topicShift.detected ? `
**TOPIC SHIFT DETECTED:**
- Previous topic: "${transitionAnalysis.topicShift.oldTopic}"
- New topic: "${transitionAnalysis.topicShift.newTopic}"
- Shift magnitude: ${(transitionAnalysis.topicShift.shiftPercentage * 100).toFixed(0)}% (${transitionAnalysis.topicShift.shiftPercentage > 0.5 ? 'significant' : 'moderate'} change)
- Similarity: ${(transitionAnalysis.topicShift.similarity * 100).toFixed(0)}%

**HOW TO RESPOND:**
- Acknowledge the transition naturally (don't be mechanical)
- Follow the tangent/transition - it's clearly where their mind wants to go
- Build on the new topic while maintaining context from previous topics
- Ask engaging questions that connect the dots between old and new topics
- Don't force them back to old topics - follow where they're going
` : ''}

${transitionAnalysis.emotionalTransition.detected ? `
**EMOTIONAL TRANSITION DETECTED:**
- From: ${transitionAnalysis.emotionalTransition.from} (${transitionAnalysis.emotionalTransition.intensityChange > 0 ? '+' : ''}${(transitionAnalysis.emotionalTransition.intensityChange * 100).toFixed(0)}% intensity change)
- To: ${transitionAnalysis.emotionalTransition.to}
- Direction: ${transitionAnalysis.emotionalTransition.direction}

**HOW TO RESPOND:**
- Validate the emotional shift if significant
- Match their energy level
- If moving from negative to positive, acknowledge the shift positively
- If moving from positive to negative, be supportive and understanding
- Don't overcorrect - follow their emotional lead
` : ''}

${transitionAnalysis.thoughtProcessChange.detected ? `
**THOUGHT PROCESS EVOLUTION DETECTED:**
- From: "${transitionAnalysis.thoughtProcessChange.from}"
- To: "${transitionAnalysis.thoughtProcessChange.to}"
- Trigger: "${transitionAnalysis.thoughtProcessChange.trigger}"
- Type: ${transitionAnalysis.thoughtProcessChange.type}

**HOW TO RESPOND:**
- Acknowledge the thought evolution naturally
- Show you're tracking their thinking process
- Ask questions that show you understand the journey: "What made you think of [new topic] while we were talking about [old topic]?"
- Connect the dots between their thoughts
` : ''}

${transitionAnalysis.intentEvolution.detected ? `
**INTENT EVOLUTION DETECTED:**
- From: ${transitionAnalysis.intentEvolution.from}
- To: ${transitionAnalysis.intentEvolution.to}
- Evolution type: ${transitionAnalysis.intentEvolution.evolutionType}

**HOW TO RESPOND:**
- Adapt your response style to match the new intent
- If deepening (e.g., venting → reflection), go deeper with them
- If expanding (e.g., reflection → decision support), broaden the conversation
- If shifting, acknowledge the shift and follow naturally
` : ''}

**CURRENT EMOTIONAL STATE:**
${currentEmotionalState ? `
- Dominant emotion: ${currentEmotionalState.dominantEmotion} (intensity: ${(currentEmotionalState.intensity * 100).toFixed(0)}%)
- Trend: ${currentEmotionalState.trend}
${currentEmotionalState.transitionFrom ? `- Transition from: ${currentEmotionalState.transitionFrom.dominantEmotion}` : ''}
${currentEmotionalState.transitionReason ? `- Reason: ${currentEmotionalState.transitionReason}` : ''}

**RESPONSE STYLE ADJUSTMENTS:**
- Match their energy level (${currentEmotionalState.intensity > 0.7 ? 'high energy' : currentEmotionalState.intensity > 0.4 ? 'moderate energy' : 'calm energy'})
- Use natural transitions (like Grok does)
- Ask engaging questions that show you're tracking their thought process
- Use personality markers consistently (their nickname if you know it, emojis if appropriate)
- Don't force them back to old topics - follow where they're going
` : ''}

**KEY PRINCIPLE**: Like Grok, you should naturally follow tangents and transitions. The user's mind is going where it wants to go - your job is to follow, validate, and engage with where they're at NOW, not where they were 3 messages ago. Build on the new topic while showing you remember the context.
` : ''}
${currentFocusLine ? `\n\n**Current focus:** ${currentFocusLine}.` : ''}
${timelineInsight && (timelineInsight.hierarchyGaps?.length ?? 0) + (timelineInsight.parallelSummary?.explicitCount ?? 0) + (timelineInsight.parallelSummary?.implicitCount ?? 0) > 0 ? `\n\n**Timeline context:** This ${timelineInsight.layer ?? 'node'} has ${timelineInsight.hierarchyGaps?.length ?? 0} empty time spans and ${timelineInsight.parallelSummary?.explicitCount ?? 0} explicit parallels (${timelineInsight.parallelSummary?.implicitCount ?? 0} overlaps). You may gently explore gaps or contextualize interruptions when relevant.` : ''}
${continuityIntent?.detected ? `

**CONTINUITY INTENT DETECTED** (confidence: ${(continuityIntent.confidence * 100).toFixed(0)}%):

The user has explicitly signaled that this moment should be persisted — they want Lorekeeper to remember, save, or track what they are sharing right now.

**WHAT WAS DETECTED:** ${continuityIntent.signals.join(', ')}
${continuityIntent.entityHints.length > 0 ? `**PEOPLE/ENTITIES MENTIONED:** ${continuityIntent.entityHints.join(', ')}` : ''}
${continuityIntent.timelineSignificant ? `**TIMELINE SIGNIFICANCE:** User explicitly referenced timeline, memoir, or creation journey.` : ''}

**HOW TO RESPOND:**
1. Open with explicit acknowledgement of what is being tracked — name the thing, name the person, name the moment. Do NOT start with a generic question.
   Example: "Got it — I'm tracking this as part of your Lorekeeper creation journey. [Name/event/feeling] is now part of your record."
2. Name what will be remembered: the entity (if any), the emotional context (if shared), the timeline significance (if stated).
3. Be factual and grounded. Do NOT be emotionally performative. Do NOT generate synthetic warmth.
4. After the acknowledgement, you may ask ONE natural follow-up only if it genuinely advances the record (e.g., a date, a relationship, a missing detail). Skip the follow-up if the record is already complete.
5. DO NOT: over-explain, ask multiple questions, roleplay feelings, invent emotions, or produce AI-therapist behavior.

**PRINCIPLE:** Sparse authentic continuity > synthetic emotional richness. The user trusts Lorekeeper to remember — show it.
` : ''}`;
}

export function buildEssenceContext(profile: any): string {
  const parts: string[] = [];

  if (profile.hopes?.length > 0) {
    parts.push(`Hopes: ${profile.hopes.slice(0, 5).map((h: any) => h.text).join(', ')}`);
  }
  if (profile.dreams?.length > 0) {
    parts.push(`Dreams: ${profile.dreams.slice(0, 5).map((d: any) => d.text).join(', ')}`);
  }
  if (profile.fears?.length > 0) {
    parts.push(`Fears: ${profile.fears.slice(0, 5).map((f: any) => f.text).join(', ')}`);
  }
  if (profile.strengths?.length > 0) {
    parts.push(`Strengths: ${profile.strengths.slice(0, 5).map((s: any) => s.text).join(', ')}`);
  }
  if (profile.weaknesses?.length > 0) {
    parts.push(`Areas for Growth: ${profile.weaknesses.slice(0, 5).map((w: any) => w.text).join(', ')}`);
  }
  if (profile.topSkills?.length > 0) {
    parts.push(`Top Skills: ${profile.topSkills.slice(0, 5).map((s: any) => s.skill).join(', ')}`);
  }
  if (profile.coreValues?.length > 0) {
    parts.push(`Core Values: ${profile.coreValues.slice(0, 5).map((v: any) => v.text).join(', ')}`);
  }
  if (profile.personalityTraits?.length > 0) {
    parts.push(`Personality Traits: ${profile.personalityTraits.slice(0, 5).map((t: any) => t.text).join(', ')}`);
  }
  if (profile.relationshipPatterns?.length > 0) {
    parts.push(`Relationship Patterns: ${profile.relationshipPatterns.slice(0, 3).map((r: any) => r.text).join(', ')}`);
  }

  return parts.length > 0 ? parts.join('\n') : 'Essence profile still developing - continue to learn about them.';
}

export async function extractIdentityFromChatMessage(
  userId: string,
  message: string,
  messageId?: string
): Promise<void> {
  try {
    const { IdentitySignalExtractor } = await import('../identityCore/identitySignals');
    const signalExtractor = new IdentitySignalExtractor();

    const entryForExtraction = {
      id: messageId || `chat-${Date.now()}`,
      text: message,
      timestamp: new Date().toISOString(),
    };

    const signals = await signalExtractor.extract([entryForExtraction]);

    if (signals.length > 0) {
      logger.debug({ userId, messageId, signalCount: signals.length }, 'Identity signals detected in chat message');

      const { IdentityCoreEngine } = await import('../identityCore/identityCoreEngine');
      const identityEngine = new IdentityCoreEngine();
      await identityEngine.processFromEntry(userId, entryForExtraction);
    }
  } catch (error) {
    logger.debug({ error, messageId }, 'Failed to extract identity from chat message');
  }
}

export function buildIdentityCoreContext(profile: any): string {
  const parts: string[] = [];

  if (profile.dimensions && profile.dimensions.length > 0) {
    const dimensionNames = profile.dimensions
      .sort((a: any, b: any) => (b.score || 0) - (a.score || 0))
      .slice(0, 5)
      .map((d: any) => `${d.name} (${((d.score || 0) * 100).toFixed(0)}%)`);
    parts.push(`Identity Dimensions: ${dimensionNames.join(', ')}`);
  }

  if (profile.conflicts && profile.conflicts.length > 0) {
    const conflictNames = profile.conflicts
      .slice(0, 3)
      .map((c: any) => `${c.conflictName || c.positiveSide} vs ${c.negativeSide}`);
    parts.push(`Internal Conflicts: ${conflictNames.join('; ')}`);
  }

  if (profile.stability) {
    const volatility = profile.stability.volatility || 0;
    const status = volatility > 0.7 ? 'High volatility (identity shifting)' :
                   volatility > 0.4 ? 'Moderate volatility (exploring)' :
                   'Stable identity';
    parts.push(`Identity Stability: ${status}`);

    if (profile.stability.anchors && profile.stability.anchors.length > 0) {
      parts.push(`Core Anchors: ${profile.stability.anchors.slice(0, 3).join(', ')}`);
    }
  }

  if (profile.projection && profile.projection.predictedIdentity) {
    parts.push(`Identity Trajectory: ${profile.projection.predictedIdentity}`);
  }

  return parts.length > 0 ? parts.join('\n') : '';
}

export async function resolveCurrentFocusLine(
  userId: string,
  currentContext?: CurrentContext
): Promise<string | undefined> {
  if (!currentContext || currentContext.kind === 'none') return undefined;
  if (currentContext.kind === 'thread' && currentContext.threadId) {
    try {
      const { threadService } = await import('../threads/threadService');
      const t = await threadService.getById(userId, currentContext.threadId);
      return t ? `thread '${t.name}'` : undefined;
    } catch {
      return undefined;
    }
  }
  if (currentContext.kind === 'timeline' && currentContext.timelineNodeId && currentContext.timelineLayer) {
    try {
      const { data } = await supabaseAdmin
        .from(
          currentContext.timelineLayer === 'chapter'
            ? 'chapters'
            : currentContext.timelineLayer === 'arc'
              ? 'timeline_arcs'
              : currentContext.timelineLayer === 'saga'
                ? 'timeline_sagas'
                : 'timeline_eras'
        )
        .select('title')
        .eq('id', currentContext.timelineNodeId)
        .eq('user_id', userId)
        .maybeSingle();
      const title = (data as { title?: string } | null)?.title;
      return title ? `${currentContext.timelineLayer} '${title}'` : undefined;
    } catch {
      return undefined;
    }
  }
  return undefined;
}
