/**
 * Character Book cards for Dating & Romance "Their connections" periphery.
 * Demo mode links these so Open profile opens a real character modal.
 */

import type { Character } from '../components/characters/CharacterProfileCard';

function peripheralCharacter(
  partial: Pick<Character, 'id' | 'name' | 'role' | 'summary'> &
    Partial<Character> & {
      anchorName: string;
      peripheralId: string;
      tier: 'suspected' | 'confirmed';
    },
): Character {
  const {
    anchorName,
    peripheralId,
    tier,
    id,
    name,
    role,
    summary,
    ...rest
  } = partial;
  return {
    id,
    name,
    first_name: name.split(' ')[0] ?? name,
    last_name: null,
    alias: [name],
    pronouns: rest.pronouns ?? 'they/them',
    archetype: 'romantic',
    role,
    status: 'active',
    importance_level: 'background',
    importance_score: tier === 'confirmed' ? 22 : 16,
    is_nickname: false,
    proximity_level: 'third_party',
    has_met: false,
    relationship_depth: 'mentioned_only',
    likelihood_to_meet: 'unlikely',
    context_of_mention: `Attributed to ${anchorName} via Dating & Romance periphery`,
    associated_with_character_ids: rest.associated_with_character_ids ?? [],
    summary,
    tags: ['romantic-peripheral', tier, 'unmet'],
    metadata: {
      relationship_type: 'romantic_peripheral',
      source: 'romantic_peripheral',
      peripheral_id: peripheralId,
      tier,
      closeness_score: 0,
      autoGenerated: true,
    },
    social_media: {},
    memory_count: 1,
    relationship_count: 0,
    ...rest,
  };
}

/** Missing romantic cast members referenced by Dating & Romance demos. */
export const MOCK_ROMANTIC_CAST_CHARACTERS: Character[] = [
  {
    id: 'char-009',
    name: 'Elena',
    first_name: 'Elena',
    last_name: null,
    alias: ['Elena'],
    pronouns: 'she/her',
    archetype: 'past_romantic',
    role: 'Rekindled ex',
    status: 'active',
    importance_level: 'supporting',
    importance_score: 58,
    is_nickname: false,
    proximity_level: 'direct',
    has_met: true,
    relationship_depth: 'close',
    summary:
      'College sweetheart with a respectful ending. You are talking again — mutual respect intact, timing still the open question.',
    tags: ['romantic', 'ex', 'rekindled', 'past'],
    metadata: {
      relationship_type: 'ex_girlfriend',
      closeness_score: 58,
      affection_score: 0.62,
      compatibility_score: 0.76,
      relationship_health: 0.64,
    },
    social_media: {},
    memory_count: 24,
    relationship_count: 2,
  },
  {
    id: 'char-riley',
    name: 'Riley',
    first_name: 'Riley',
    last_name: null,
    alias: ['Riley'],
    pronouns: 'they/them',
    archetype: 'past_romantic',
    role: 'Ghosted hookup',
    status: 'inactive',
    importance_level: 'supporting',
    importance_score: 42,
    is_nickname: false,
    proximity_level: 'direct',
    has_met: true,
    relationship_depth: 'casual',
    summary:
      'Summer party circuit overlap with Sam. Chemistry early on, then silence — left on read for weeks.',
    tags: ['romantic', 'ghosted', 'past', 'hookup'],
    metadata: {
      relationship_type: 'hooking_up',
      closeness_score: 35,
      affection_score: 0.4,
      relationship_health: 0.1,
      no_contact: true,
    },
    social_media: {},
    memory_count: 8,
    relationship_count: 1,
  },
];

export const MOCK_ROMANTIC_PERIPHERAL_CHARACTERS: Character[] = [
  peripheralCharacter({
    id: 'romantic-periph-marcus',
    name: 'Marcus',
    pronouns: 'he/him',
    role: "Sam's suspected side partner",
    summary:
      'Named in chat as someone Sam was texting during your situationship. You have never met him.',
    anchorName: 'Sam',
    peripheralId: 'periph-sam-marcus',
    tier: 'suspected',
    associated_with_character_ids: ['char-003'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-dana',
    name: 'Dana',
    pronouns: 'she/her',
    role: "Alex's work crush (hearsay)",
    summary:
      "Alex mentioned talking to someone at work — LoreBook attributed Dana from that coworker thread.",
    anchorName: 'Alex',
    peripheralId: 'periph-alex-coworker',
    tier: 'suspected',
    associated_with_character_ids: ['char-001'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-jamie',
    name: 'Jamie',
    pronouns: 'they/them',
    role: "Alex's ex",
    summary: 'Alex said her ex Jamie still texts on birthdays — hearsay only from your conversations.',
    anchorName: 'Alex',
    peripheralId: 'periph-alex-ex-jamie',
    tier: 'confirmed',
    associated_with_character_ids: ['char-001'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-parker',
    name: 'Parker',
    pronouns: 'they/them',
    role: "Jordan's studio hang",
    summary: 'Studio gossip says Jordan and Parker have been hanging out a lot.',
    anchorName: 'Jordan',
    peripheralId: 'periph-jordan-studio-partner',
    tier: 'suspected',
    associated_with_character_ids: ['char-002'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-devon',
    name: 'Devon',
    pronouns: 'they/them',
    role: "Taylor's studio crush",
    summary: 'A friend said Taylor had a thing for Devon during the last studio show.',
    anchorName: 'Taylor',
    peripheralId: 'periph-taylor-studio-crush',
    tier: 'suspected',
    associated_with_character_ids: ['char-004'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-quinn',
    name: 'Quinn',
    pronouns: 'they/them',
    role: "Morgan's rebound",
    summary: 'Someone said Morgan rebounded hard with Quinn after things burned out.',
    anchorName: 'Morgan',
    peripheralId: 'periph-morgan-rebound',
    tier: 'suspected',
    associated_with_character_ids: ['char-005'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-avery',
    name: 'Avery',
    pronouns: 'they/them',
    role: "Casey's lunch partner",
    summary: 'Office gossip says Casey and Avery take lunch together every day and may be dating.',
    anchorName: 'Casey',
    peripheralId: 'periph-casey-coworker',
    tier: 'suspected',
    associated_with_character_ids: ['char-006'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-blake',
    name: 'Blake',
    pronouns: 'they/them',
    role: "Casey's ex",
    summary: 'Casey mentioned their ex Blake when talking about bad timing.',
    anchorName: 'Casey',
    peripheralId: 'periph-casey-ex',
    tier: 'confirmed',
    associated_with_character_ids: ['char-006'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-cameron',
    name: 'Cameron',
    pronouns: 'they/them',
    role: 'Riley fling (rumor)',
    summary: 'A mutual said Riley ghosted because Cameron showed up.',
    anchorName: 'Riley',
    peripheralId: 'periph-riley-new-fling',
    tier: 'suspected',
    associated_with_character_ids: ['char-riley'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-sky',
    name: 'Sky',
    pronouns: 'they/them',
    role: "Nova's new partner (rumor)",
    summary: 'Someone posted that Nova is with Sky now.',
    anchorName: 'Nova',
    peripheralId: 'periph-nova-new-person',
    tier: 'suspected',
    associated_with_character_ids: ['char-007'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-maya',
    name: 'Maya',
    pronouns: 'she/her',
    role: "Elena's college ex",
    summary: 'Elena dated Maya for a while after college before things settled.',
    anchorName: 'Elena',
    peripheralId: 'periph-elena-college-friend',
    tier: 'confirmed',
    associated_with_character_ids: ['char-009'],
  }),
  peripheralCharacter({
    id: 'romantic-periph-chris',
    name: 'Chris',
    pronouns: 'he/him',
    role: 'Elena talking-to (rumor)',
    summary:
      'A mutual friend said Elena might still be talking to Chris while reconnecting with you.',
    anchorName: 'Elena',
    peripheralId: 'periph-elena-current-rumor',
    tier: 'suspected',
    associated_with_character_ids: ['char-009'],
  }),
];

const BY_ID = new Map(
  [...MOCK_ROMANTIC_CAST_CHARACTERS, ...MOCK_ROMANTIC_PERIPHERAL_CHARACTERS].map((c) => [c.id, c]),
);

export function getMockRomanticPeripheralCharacters(): Character[] {
  return [...MOCK_ROMANTIC_CAST_CHARACTERS, ...MOCK_ROMANTIC_PERIPHERAL_CHARACTERS];
}

export function getMockRomanticBookCharacterById(id: string): Character | undefined {
  return BY_ID.get(id);
}

/** Merge demo romantic periphery/cast into a Character Book list without duplicates. */
export function mergeRomanticDemoCharacters(base: Character[]): Character[] {
  const byId = new Map(base.map((c) => [c.id, c]));
  for (const c of getMockRomanticPeripheralCharacters()) {
    if (!byId.has(c.id)) byId.set(c.id, c);
  }
  return [...byId.values()];
}
