/**
 * ConversationMetadata — typed contract for conversation_sessions.metadata
 *
 * Ownership rules (DO NOT mutate from the wrong owner):
 *
 *   messages         → useChatThreads (debounced client PATCH, UI format)
 *   titleSource      → ConversationTitleService (server, set on auto-gen or user rename)
 *   subtitle         → ConversationTitleService (server, generated alongside title)
 *   dominantEntities → ingestion pipeline (server, async after extraction)
 *   emotionalTone    → ingestion pipeline (server, async)
 *   lastModeDecision → chat route (server, set on each AI response)
 *   narrativeThemes  → ingestion pipeline (server, async)
 *   chat_session_id  → legacy (read-only, not written by new code)
 *   entity_*         → entity-scoped session creation (read-only after creation)
 *
 * Mutation strategy:
 *   All server-side fields are written via PATCH .update({ metadata: { ...existing, ...patch } })
 *   so existing keys are never clobbered. The client only writes `messages` (and reads everything).
 */

export interface ConversationMetadata {
  // ── Message store (UI format) ───────────────────────────────────────────────
  /** Full message array in UI format, debounced-synced from the client. */
  messages?: SerializedMessage[];

  // ── Title governance ────────────────────────────────────────────────────────
  /**
   * 'auto'  = generated by AI (never overwrite the user's rename)
   * 'user'  = manually renamed (auto-generation permanently suppressed)
   * absent  = title was never generated (still "New chat")
   */
  titleSource?: 'auto' | 'user';

  /**
   * Optional secondary descriptor — concise category label.
   * Examples: "Architecture Session", "Character Reflection", "Memory Recall"
   * Set by ConversationTitleService alongside the title. Never set by client.
   */
  subtitle?: string;

  // ── Cognition context (server-authored, async) ───────────────────────────────
  /** Top entity names mentioned across this conversation (from ingestion pipeline). */
  dominantEntities?: string[];

  /**
   * Overall emotional register detected from the conversation.
   * Examples: "reflective", "analytical", "urgent", "exploratory"
   */
  emotionalTone?: string;

  /**
   * Last mode the router chose for this conversation.
   * Mirrors Message.modeDecision.mode from the most recent AI response.
   */
  lastModeDecision?: string;

  /** Recurring narrative themes detected by the ingestion pipeline. */
  narrativeThemes?: string[];

  // ── Legacy / entity-scoped (read-only) ─────────────────────────────────────
  chat_session_id?: string;
  entity_type?: string;
  entity_id?: string;
  is_entity_scoped?: boolean;
}

/**
 * Minimal message shape stored in metadata.messages (UI format, serialised).
 * Full Message type lives in ChatMessage.tsx — this is the storage-safe subset.
 */
export interface SerializedMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string; // ISO string
  isSystemMessage?: boolean;
  // Cognition observability — carried through storage so thread restore works
  modeDecision?: { mode: string; confidence: number; reasoning: string };
  ragStats?: { sourceCount: number; cacheHit: boolean; retrievalMs: number; contextItems: number };
  sources?: unknown[];
  [key: string]: unknown;
}

/** What the POST /threads/:id/title endpoint returns after generation. */
export interface TitleGenerationResult {
  title: string;
  subtitle?: string;
}
