/** Client-side mirror of apps/server/src/services/lexical/lexicalPreviewPatterns.ts */

export type PreviewPattern = {
  re: RegExp;
  type: string;
  subtype?: string;
  colorKey: string;
  confidence: number;
  needsReview?: boolean;
  priority: number;
};

export const PREVIEW_PATTERNS: PreviewPattern[] = [
  {
    re: /\bat\s+[A-Z][\w']*(?:'s)?\s+in\s+[A-Z][a-z]+\b/g,
    type: 'DEPLOYMENT_SITE',
    subtype: 'WORKSITE',
    colorKey: 'worksite',
    confidence: 0.86,
    needsReview: true,
    priority: 35,
  },
  {
    re: /\b(?<=worked\s+at\s)[A-Z][\w]*(?:\s+[A-Z][\w]*)+\b/g,
    type: 'ORGANIZATION',
    subtype: 'EMPLOYER',
    colorKey: 'organization',
    confidence: 0.92,
    priority: 34,
  },
  {
    re: /\b(?<=as\s+a\s)[a-z][\w\s-]+?(?=\s+with|\s*[,.]|$|\s+at\b|\s+for\b)/gi,
    type: 'ROLE',
    subtype: 'JOB_TITLE',
    colorKey: 'role',
    confidence: 0.88,
    needsReview: true,
    priority: 33,
  },
  {
    re: /\bArUco\s+calibration\b/gi,
    type: 'SKILL',
    subtype: 'PROFESSIONAL_SKILL',
    colorKey: 'skill',
    confidence: 0.88,
    priority: 32,
  },
  {
    re: /\blive\s+robot\s+support\b/gi,
    type: 'WORK_ACTIVITY',
    subtype: 'FIELD_OPERATIONS',
    colorKey: 'work_activity',
    confidence: 0.84,
    priority: 31,
  },
  {
    re: /\bgripper\s+swaps?\b/gi,
    type: 'TASK',
    subtype: 'MAINTENANCE_TASK',
    colorKey: 'task',
    confidence: 0.82,
    needsReview: true,
    priority: 30,
  },
  {
    re: /\b(?<=with\s)[A-Z][a-z]+(?=\s+and\b)/g,
    type: 'PERSON',
    subtype: 'COWORKER',
    colorKey: 'person',
    confidence: 0.85,
    priority: 28,
  },
  {
    re: /\b(?<=and\s)[A-Z][a-z]+(?=\s*[,.]|$|\s+(?:I|at)\b)/g,
    type: 'PERSON',
    subtype: 'COWORKER',
    colorKey: 'person',
    confidence: 0.85,
    priority: 27,
  },
  {
    re: /\b(?<=in\s)[A-Z][a-z]+(?=\s*[,.]|$)/g,
    type: 'PLACE',
    subtype: 'CITY',
    colorKey: 'place',
    confidence: 0.84,
    priority: 26,
  },
  {
    re: /\bnever had (?:any other )?friends like him\b/gi,
    type: 'EMOTIONAL_SIGNIFICANCE',
    subtype: 'IRREPLACEABILITY',
    colorKey: 'emotional_significance',
    confidence: 0.93,
    needsReview: true,
    priority: 24,
  },
  {
    re: /\bbest friend\b/gi,
    type: 'RELATIONSHIP',
    subtype: 'CLOSE_FRIEND',
    colorKey: 'relationship',
    confidence: 0.92,
    needsReview: true,
    priority: 23,
  },
  {
    re: /\bbefore the Pandemic\b/gi,
    type: 'TIME_PERIOD',
    subtype: 'HISTORICAL_MARKER',
    colorKey: 'time',
    confidence: 0.9,
    needsReview: true,
    priority: 22,
  },
  {
    re: /\b(?:used to )?go to shows in LA(?:\s+all the time)?\b/gi,
    type: 'EVENT',
    subtype: 'RECURRING_EVENT',
    colorKey: 'event',
    confidence: 0.91,
    priority: 21,
  },
  {
    re: /\bCode Red\b/g,
    type: 'EVENT',
    subtype: 'EVENT_OR_VENUE',
    colorKey: 'event',
    confidence: 0.92,
    needsReview: true,
    priority: 36,
  },
  {
    re: /\bska shows?\b/gi,
    type: 'MUSIC_GENRE',
    subtype: 'SKA',
    colorKey: 'interest',
    confidence: 0.88,
    priority: 19,
  },
  {
    re: /\b(?:a bunch of )?ska shows?\b/gi,
    type: 'MUSIC_GENRE',
    subtype: 'SKA',
    colorKey: 'interest',
    confidence: 0.86,
    priority: 18,
  },
  {
    re: /\b[A-Z][a-z]+(?:\s+(?!Class\b|Team\b|Club\b|Break\b|Street\b|Avenue\b|Road\b|Boulevard\b|Red\b)[A-Z][a-z]+)+\b/g,
    type: 'PERSON',
    subtype: 'FULL_NAME',
    colorKey: 'person',
    confidence: 0.9,
    priority: 17,
  },
  {
    re: /\b(?:my\s+|our\s+)?friends?\s+(?:from|on|in)\s+(?:the\s+|my\s+|our\s+)?[a-z]+\s+team\b/gi,
    type: 'GROUP',
    subtype: 'SOCIAL_GROUP',
    colorKey: 'group',
    confidence: 0.82,
    needsReview: true,
    priority: 16,
  },
  {
    re: /\b[a-z]+\s+club\s+at\s+school\b/gi,
    type: 'GROUP',
    subtype: 'SCHOOL_CLUB',
    colorKey: 'group',
    confidence: 0.88,
    needsReview: true,
    priority: 15,
  },
  {
    re: /\bdetention\b/gi,
    type: 'EVENT',
    subtype: 'SCHOOL_DISCIPLINE_EVENT',
    colorKey: 'event',
    confidence: 0.85,
    needsReview: true,
    priority: 14,
  },
  {
    re: /\blunch\s+break\b/gi,
    type: 'TIME_PERIOD',
    subtype: 'SCHOOL_DAY_TIME',
    colorKey: 'time',
    confidence: 0.85,
    priority: 13,
  },
  {
    re: /\byesterday\b/gi,
    type: 'TIME_PERIOD',
    subtype: 'RELATIVE_DATE',
    colorKey: 'time',
    confidence: 0.9,
    priority: 12,
  },
  {
    re: /\b(?:football|soccer|basketball|baseball|track|swim|debate|chess)\s+team\b/gi,
    type: 'GROUP',
    subtype: 'SCHOOL_TEAM',
    colorKey: 'group',
    confidence: 0.8,
    priority: 11,
  },
  {
    re: /\bfavorite\s+summer\s+clothes\b/gi,
    type: 'PREFERENCE',
    subtype: 'OBJECT_CATEGORY',
    colorKey: 'preference',
    confidence: 0.8,
    needsReview: true,
    priority: 10,
  },
  {
    re: /\b(?:my|our)\s+school\s+[A-Z][\w]*(?:\s+[A-Z][\w]*)*\s+Class\b/gi,
    type: 'GROUP',
    subtype: 'SCHOOL_CLASS',
    colorKey: 'group',
    confidence: 0.92,
    priority: 9,
  },
  {
    re: /\blast\s+summer\b/gi,
    type: 'TIME_PERIOD',
    subtype: 'RELATIVE',
    colorKey: 'time',
    confidence: 0.88,
    needsReview: true,
    priority: 8,
  },
  {
    re: /\bJapan\b/g,
    type: 'PLACE',
    subtype: 'country',
    colorKey: 'place',
    confidence: 0.95,
    priority: 7,
  },
  {
    re: /\bLA\b/g,
    type: 'PLACE',
    subtype: 'city_or_region',
    colorKey: 'place',
    confidence: 0.9,
    priority: 6,
  },
  {
    re: /\b(?:was\s+so\s+|it\s+was\s+)hot\b/gi,
    type: 'WEATHER_CONTEXT',
    subtype: 'CLIMATE',
    colorKey: 'weather',
    confidence: 0.82,
    priority: 5,
  },
  {
    re: /\bwent\s+on\s+the\s+trip\b/gi,
    type: 'EVENT',
    subtype: 'EVENT_TRAVEL',
    colorKey: 'event',
    confidence: 0.85,
    priority: 4,
  },
  {
    re: /\bJapanese\b/g,
    type: 'LANGUAGE',
    subtype: 'SUBJECT',
    colorKey: 'language',
    confidence: 0.86,
    priority: 2,
  },
];
